### PR TITLE
Clear cached property when validation is off

### PR DESCRIPTION
**Pull request by weiliangjin2021**
Fixes PEC2D issue brought up by @QimingFlex

### CODE REVIEW

**Review by tylerflex — APPROVED** [review]
Approved after Changelog

**Comment by QimingFlex** [comment]
Thanks @weiliangjin2021 ! I'm trying to understand the logics behind `subsection`. Why do we skip `validate_geometries` when taking subsection for mode solver?

**Comment by weiliangjin2021** [comment]
> Thanks @weiliangjin2021 ! I'm trying to understand the logics behind `subsection`. Why do we skip `validate_geometries` when taking subsection for mode solver?

Please checkout this PR: https://github.com/flexcompute/tidy3d/pull/2022

**Comment by QimingFlex** [comment]
> > Thanks @weiliangjin2021 ! I'm trying to understand the logics behind `subsection`. Why do we skip `validate_geometries` when taking subsection for mode solver?
> 
> Please checkout this PR: #2022

Thanks and approved!

**Review by QimingFlex — APPROVED** [review]

**Pull request merged**
