### PR TITLE
Change missing source from warning to info (#813)

### PR DESCRIPTION
**Pull request by lucas-flexcompute**
Also included a flag in the pre upload validator to optionally raise an error if no sources are present in the simulation. This flag is true by default on `run` and manual job creation, but false for the mode solver. It cannot be changed from `run` (only in `Job` or `Batch`), because simulations with no sources should be very rare and we already have a lot of arguments in `run`.

### CODE REVIEW

**Review by tylerflex — COMMENTED** [review]
Looks good to me. only suggestion is maybe we dont need to add this to containers or web.upload basically there should never be a time that we'd want to upload without sources?

**Comment by lucas-flexcompute** [comment]
In the original issue you mentioned the user might upload only to view ModeMonitorData or PermittivityData results. Is that not the case any longer?

**Comment by tylerflex** [comment]
Hm, well I think that might have been something I was suggesting as a workaround to these not having their own separate web services, but my impression was that @momchil-flex didn't want to encourage this because it wastes our resources correct? so yea I think in this case it's probably good how you have it set up now.

**Comment by tylerflex** [comment]
I'm still not sure we need it in containers because it seems unlikely that simulations in the containers would need to change the default behavior.

**Review by tylerflex — APPROVED** [review]

**Comment by tylerflex** [comment]
I forgot, can we also add a "changed" item in changelog? just saying that we no longer will allow upload of simulation without sources or something?

**Pull request merged**
