### PR TITLE
:package: BUILD: Fix the trigger develop cli action to sync branches

### PR DESCRIPTION
**Pull request by daquinteroflex**
Hello! I think we need to merge this as soon as we can in order for the develop actions to begin running from the branch that triggered the build.

Also I found a bug on tidy3d-develop-cli that was testing the develop installation only on the develop  branch, but not on the actual branches where the commit was created in which I'm fixing.

Note that the develop action won't be fixed until we merge this into develop

### CODE REVIEW

**Comment by momchil-flex** [comment]
Since we merged #1650 to pre/2.7, this here is only relevant if we want to make a 2.6.5 right?

**Comment by daquinteroflex** [comment]
Unfortunately, this PR is relevant if we want all develop-cli tests to pass on all branches including pre-/2.7. This is becuase of the way that the "trigger" action occurs when the "run tests" workflow has completed. It can only trigger if the action is in the main branch. However, our action in the main develop branch had a bug that it was only checking out the develop branch, rather than the branch that triggered the action on the tidy3d-develop-cli action. This PR fixes that.

**Comment by momchil-flex** [comment]
Ah ok.

**Comment by momchil-flex** [comment]
@tylerflex you're marked as reviewer here

**Review by tylerflex — APPROVED** [review]

**Pull request merged**
