### PR TITLE
remove default logging level and rich.pretty

### LINKED ISSUE #650: tidy3d module import side effects
when importing tidy3 module there are two strange side effects that I don't really want and seem unnecessary

1. the stdout format changes. This causes plots to be duplicated, and makes it incompatible with other packages.
2. the logging level changes to everything so I can see logging even INFO messages

See this [notebook](https://gdsfactory.github.io/ubc/notebooks/11_sparameters.html)

I think is happening in the `__init__.py`
```
# make all stdout and errors pretty
pretty.install()
# traceback.install()
log.info(f"Using client version: {__version__}")
```

@tylerflex 
@momchil-flex

### PR DESCRIPTION
**Pull request by tylerflex**
fixes #650 replaces #651

### CODE REVIEW

**Review by dbochkov-flexcompute — APPROVED** [review]

**Comment by dbochkov-flexcompute** [comment]
a bit sad to see `Using client version: {__version__}` go :)

**Comment by tylerflex** [comment]
Yea, actually after some internal discussion, I think we want to keep INFO as the default logging level for now. @joamatab I made a branch [`fix/log_level_reset`](https://github.com/flexcompute/tidy3d/tree/fix/log_level_reset) where I couldn't reproduce any resetting of the root log level after importing tidy3d. maybe before we do any changes to our logging, could you make a test that identifies the issue and we can try to address it directly. I might not be understanding the problem well enough. Thanks, closing this for now.

**Comment by joamatab** [comment]
The issue is that other packages that can use tidy3d may rely on the tidy3d not changing the default logging level

**Comment by tylerflex** [comment]
yea I Agee that this is a problem, but I can't seem to reproduce it myself in a test or in my shell.

**Pull request closed without merging**
