### PR TITLE
2.5 changes

### PR DESCRIPTION
**Pull request by tylerflex**
Just a few things we were going to change for 2.5, before I forget. Might be more, so we can keep this open and add to it as needed or merge whenever.

- Python 3.7 no longer guaranteed to be supported.
- Remove colocation deprecation warning.

### CODE REVIEW

**Comment by tylerflex** [comment]
@momchil-flex we should probably get this in sooner rather than later. Just want to confirm that we want to remove this colocation warning and also that this PR handles it the right way.

**Review by momchil-flex — APPROVED** [review]
Looks good, what do you think about officially requiring python > 3.7 since we won't be testing?

**Comment by tylerflex** [comment]
yea that's a good point, I just pushed a separate commit (probably fine for them to be separate) to restrict this, and updated changelog.

**Comment by tylerflex** [comment]
note: I think tests fail because I guess it's using the `pre/2.5` `tox.ini` (which includes python3.7) instead of the one from this PR.

**Comment by tylerflex** [comment]
actually it was because I forgot to exclude from the workflow, should be fixed.

**Pull request merged**
