### PR TITLE
Fix syntax bug in mode solver

### PR DESCRIPTION
**Pull request by shashwat-sh**
Fixed a very silly bug in the recent mode solver improvements which was causing the preconditioner to always be applied.

### CODE REVIEW

**Review by tylerflex — APPROVED** [review]

**Comment by tylerflex** [comment]
note, I think this would also work (using `any()` instead of `np.any()`)
```py
if any(any_pec(i) for i in [eps_xx, eps_yy, eps_zz]):
```

**Comment by shashwat-sh** [comment]
> note, I think this would also work (using `any()` instead of `np.any()`)
> 
> ```python
> if any(any_pec(i) for i in [eps_xx, eps_yy, eps_zz]):
> ```

Yep that seems to work too. Do you think it's better one way or another?

**Comment by tylerflex** [comment]
either is fine with me, just was curious about it so tried it out. Do you want to merge this for the 2.2.1 patch or wait for weiliang?

**Comment by shashwat-sh** [comment]
I think we should merge it in asap, it's a tiny bug but has potentially large consequences

**Comment by tylerflex** [comment]
ok, could you add a line in the changelog, also let's go with `any()` instead of `np.any()` for just 3 elements I think this makes more sense. I'll merge it after and then release 2.2.1

**Pull request merged**
