### PR TITLE
:books: Multiple docs fixes and improvements

### PR DESCRIPTION
**Pull request by daquinteroflex**
Live at https://docs.flexcompute.com/projects/tidy3d/en/demo-test-fix_docs_builds/development/documentation.html

- [x] Fixes https://flow360.atlassian.net/browse/SCEM-7774
- [x] Faster docs build
- [x] Reduces number of sphinx warnings and docs issues
     - [x] More consistent title levels
     - [x] Adding missing documentation onto stub files
- [X] Adds the latest lectures on the webcenter
- [X] Ugly attr directory inclusion on each class in the `pre/2.7` docs

Supersedes https://github.com/flexcompute/tidy3d/pull/1745

image

### CODE REVIEW

**Comment by daquinteroflex** [comment]
Hi @tylerflex, just fyi you've already reviewed/approved most of this in https://github.com/flexcompute/tidy3d/pull/1745 . This PR does the requested Jira fix and also removes the stuff that didn't work from the other old PR of the multiple docs improvements.

**Review by tylerflex — APPROVED** [review]
Thanks! it looks good to me. I'm not sure if you need someone else on the team to take a look? as I couldn't understand everything here. but as long as it fixes the issues I think it's good to me!

**Comment by daquinteroflex** [comment]
Sounds good I've added @jwang1231  who requested the Jira fix.

**Comment by jwang1231** [comment]
Double checked. The duplicated 'Documentation' has been removed from the tree node.

**Comment by daquinteroflex** [comment]
Nice, merging now and so this will be live on the next docs release.

**Pull request merged**
