### PR TITLE
added test to check if intersections caught where two boxes touch

### PR DESCRIPTION
**Pull request by tylerflex**
@shashwat-sh could you modify this branch to try to get this test to fail? and then we can look into the issue behind it.

### CODE REVIEW

**Comment by shashwat-sh** [comment]
@tylerflex I'm able to trigger the errors by trying different values of L - see the latest commit. Maybe it's a numerical precision thing?

**Comment by tylerflex** [comment]
Yea so it's this line that gets triggered, which returns no intersections.

https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/components/geometry.py#L770-L773

if I breakpoint there and look at the variables (x0 = 5, L=0.24)

```py
Lz / 2 = 0.24 / 2 = 0.12
```

for box with center at 5-0.12

```py
np.abs(box.center[0] - x0) = dz = abs(4.88 - 5) = 0.1200000000000001
```

for box with center at x = 5+1.2

```py
np.abs(box.center[0] - x0) = dz = abs(5.12 - 5) = 0.1200000000000001
```

So yea it's numerical precision issue in that both subtractions seem to add a bit on the end.
image

Any good ideas on how to fix? maybe just add a fp_eps to the intersection check? ie
```py
        if dz > Lz / 2:
            return []
```
becomes
```py
        if dz > Lz / 2 + fp_eps:
            return []
```

@momchil-flex ?

**Comment by shashwat-sh** [comment]
Yeah I think that kind of `fp_eps` check is common in floating point geometry operations. However, it may be good to set the tolerance in units of a relevant length scale so that the comparison works regardless of the units, e.g.,

```
tol = 1e-6 # specified a relative tolerance, could just be fp_eps
if number_1 > number_2 + tol * reference_length:
    # could use the min grid spacing as the reference length, for example
    ...
```

If some day issues like this become a bigger pain, some geometry processing libraries use the strategy of just converting everything to ints with a multiplicative "precision" factor. E.g. 5.0 and 5.001 with a `precision_factor` of 100000 are converted to the ints 500000 and 500100 so there's never any ambiguity. Same idea as the `fp_eps` approach, but maybe more convenient because once converted to ints, all comparisons can be simple. In your example, if a reasonable `precision` were to be applied, both numbers would be converted to the same int, e.g., 12000.

**Comment by tylerflex** [comment]
`fp_eps` passes the test at least, but yea the other idea is a good one. I dont know how "loose" we want to be with the precision checking, because someone might be actually checking `fp_eps` outside of the geometry to ensure that it's not present, so maybe we want to not capture the intersections in that case. For now I think `fp_eps` is maybe the best approach until we run into more of an issue?

**Comment by shashwat-sh** [comment]
image
The plot looks good now! Just curious, since the two boxes are of different sizes, how does the code pick which one to display? Or is it just the intersected surface that's displayed?

**Comment by tylerflex** [comment]
great! It will just plot whatever intersections get captured, one after another, in the order that they appear in the structures tuple.

**Review by shashwat-sh — APPROVED** [review]

**Pull request merged**
