### PR TITLE
Fix another geos error in _filter_structures_plane

### PR DESCRIPTION
**Pull request by weiliangjin2021**

### CODE REVIEW

**Comment by weiliangjin2021** [comment]
Somehow `normalize()` fixes `shapely.errors.GEOSException: TopologyException: side location conflict at ..... This can occur if the input geometry is invalid.`. It works without `buffer(0`), but I just keep it to be safe.

I also shift things around to make it easier to follow.

**Review by tylerflex — APPROVED** [review]
looks good to me, but this kind of shapely manipulation is outside of my knowledge at this point so feel free to get another review if needed.

**Review by momchil-flex — APPROVED** [review]
Approving if tests pass and this fixes the error users encountered, but I don't understand this either. :D @lucas-flexcompute ?

**Comment by lucas-flexcompute** [comment]
I've always disliked the `buffer(0)` hack, although that seems to be the only working option in some cases. And I guess `normalize` does more than the docs imply. There might be other places in the frontend where we use `buffer(0)` or `make_valid` that might also benefit from the `normalize` call. I don't think we need to test that in this PR, but we should remember that the next time we see GEOS/shapely errors.

**Review by lucas-flexcompute — APPROVED** [review]

**Pull request merged**
