### PR TITLE
refactor Box.surfaces and Source.injection_axis

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Comment by shashwat-sh** [comment]
Could you clarify why `injection_axis` should be protected? I used it a fair bit on the backend for TFSF - I guess disabling that pylint warning everywhere should work, but I'm not sure I see the advantage. For TFSF, an alternative could be to have an exposed `injection_axis` just for that source.

**Comment by tylerflex** [comment]
Hm, so here was the problem, the `injection_axis` was set as both a property and a field.
So here was the problem:
1. The `dir_vector` property needed to check if `hasattr(self, 'injection_axis')` to know whether to be defined or not.
2. This seemed like a less ideal organization, so I added an `injection_axis` property at the base `Source` level, with `None` as default.
3. The problem with this was that one could not then add the `injection_axis` field because the property already existed.
4. So I made the property underscored and left the field as is.

Since this is used a lot in the backend (should have considered that) I think I should just revert these changes as it's not worth any marginal benefit, unless you can think of a better solution.

**Comment by shashwat-sh** [comment]
Actually, this may not be an issue. I just remembered that in TFSF, I need to define an [`injection_axis` field](https://github.com/flexcompute/tidy3d/blob/9106e1a870a0b3de9ccfff9d973f775eab1abfdb/tidy3d/components/source.py#L815) anyway, because it needs to be set by the user - it can't be a property. Also, TFSF is a volume source and does not inherit from `PlanarSource`, so it doesn't inherit that property anyway.

**Comment by shashwat-sh** [comment]
I'll look through the rest of the backend code and run the tests to see if it requires any backend changes.

**Comment by tylerflex** [comment]
thanks!

**Comment by tylerflex** [comment]
it's a bit ugly, but maybe I could also add the original `injection_axis` property back into Planar, which would guarantee this still works.

**Comment by tylerflex** [comment]
I just went ahead and put that original property back in but kept the private property. so it should be backwards compatible.

**Comment by shashwat-sh** [comment]
Ok, I'm just running all backend tests just in case, I'll confirm when that's done. Otherwise, looks good.

**Comment by shashwat-sh** [comment]
(also because `surfaces` is also used a lot in backend code in a variety of scenarios and the various corner cases caused a lot of grief in the past)

**Review by shashwat-sh — APPROVED** [review]
Looks good, all backend tests pass locally. I won't be able to test this with TFSF until the latter is merged in, but I think it'll be fine.

**Pull request merged**
