### PR TITLE
Fix a few unstable materials in material_library

### PR DESCRIPTION
**Pull request by weiliangjin2021**
Performed a scan of all materials in the material library, and find that `Cu_JohnsonChristy1972` and `Ni_JohnsonChristy1972` are unstable. `TiOx_Horib` is stable with a smaller courant number since it has `eps_inf<1`. But the caveat is that no subpixel averaging will be performed for structures made of this material in the simulation. So a  `TiOx_HoribStable` of `eps_inf=1` is added.

### CODE REVIEW

**Review by tylerflex — APPROVED** [review]

**Review by lucas-flexcompute — APPROVED** [review]

**Comment by lucas-flexcompute** [comment]
Is it wise to keep the unstable version of TiOx in the library? Same goes for Fused Silica, for example, where there seems to be a PML stable version and what I assume might be an unstable version. It's confusing from a user perspective.

**Comment by weiliangjin2021** [comment]
> Is it wise to keep the unstable version of TiOx in the library? Same goes for Fused Silica, for example, where there seems to be a PML stable version and what I assume might be an unstable version. It's confusing from a user perspective.

One difference between `TiOx_Horib` and `TiOx_HoribStable` is that the former is directly from the reference, while the latter is fitted. So if we remove the former, it might also be confusing? And it's only unstable if we don't use a smaller time step size. 

As for the PML stable Fused silica, the unstable version is still stable if the material doesn't extend into PML.

**Comment by weiliangjin2021** [comment]
Another reason for keeping the original version of fused silica is also that it's directly based on the reference which provides a Sellmeier formula, and the PMLStable version is fitted.

**Comment by lucas-flexcompute** [comment]
In that case, we should provide this information in the documentation and also in the docstring of the material, so that it is easier to chose a variant from `help(td.material_library["TiOx"])`, for example.

**Comment by weiliangjin2021** [comment]
Good point. But there is no place to add this information in the current script. How about add a field in `VariantItem` to store the info (in a separate PR)?

**Review by xin-flex — APPROVED** [review]

**Pull request merged**
