### PR TITLE
eps_model eval at `td.inf` if freq is None

### PR DESCRIPTION
**Pull request by tylerflex**
Makes this explicit and fixes `nan` coming from `inf * 0` in `PoleResidue`

### CODE REVIEW

**Comment by weiliangjin2021** [comment]
When `frequency_range` is not None, `mat.eps_model(None)` will return `(nan+nanj)`. Is this expected?

**Comment by tylerflex** [comment]
no, it's not expected.  thanks. I'll have to look into that again.

**Comment by tylerflex** [comment]
what was the frequency range where you observe this?  I guess if `eps_model(None)` implies `freq=inf`, so we should be able to handle in principle if the frequency bounds upper limit is `inf`.

**Comment by weiliangjin2021** [comment]
The material is `BK7_Zemax`, so the frequency bound is finite.

**Review by weiliangjin2021 — APPROVED** [review]

**Pull request merged**
