### PR TITLE
sources with user-supplied E, H, J, M data.

### PR DESCRIPTION
**Pull request by tylerflex**
Basic idea:

Defines `ScalarField(x, y, z, values)` object, accepting the `x`, `y`, `z` coordinate values (1d) and the values (3d) of the field or current at each location.

Then, defines both `CustomCurrentSource(Jx, Jy, Jz, Mx, My, Mz)`  and `CustomFieldSource(Ex, Ey, Ez, Hx, Hy, Hz)` objects to combine all of these supplied values to inject either a source directly or the equivalent currents required to construct a desired field pattern.

### CODE REVIEW

**Comment by tylerflex** [comment]
## Questions:

1. `CustomFieldSource` / `CustomCurrentSource` or just `FieldSource`, `CurrentSource` or other?
2. convenient `@classmethod`constructors?  eg. `.from_SimulationData(sim_data, monitor_name)`?
3. other source parameters in main constructor? ie `CustomFieldSource(Ex=Ex, source_time=gaussian_pulse, size=(1,1,1))`

**Comment by momchil-flex** [comment]
Why not reuse `ScalarFieldData` instead of defining `ScalarField`?

**Comment by tylerflex** [comment]
`ScalarFieldData` inherits with a set of different methods and config, so I was worried it would clash with something that was just a `Tidy3dBaseModel` object.  In the data.py rewrite, maybe we can unify them, though.

**Comment by tylerflex** [comment]
closing as data completely refactored, see #447

**Pull request closed without merging**
