### PR TITLE
smatrix uses batch instead of batch_data

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Comment by tylerflex** [comment]
one line to modify the SMatrix notebook when it is merged (tested in notebook already)

**Comment by momchil-flex** [comment]
This looks fine; separately - seems like we still don't have a way to load a batch that you have already downloaded?

**Comment by tylerflex** [comment]
`batch.load()` will detect that it's already downloaded by the filename (includes task_id) and won't do it again.

**Comment by momchil-flex** [comment]
Oh, great!

**Review by momchil-flex — APPROVED** [review]

**Pull request merged**
