### PR TITLE
remove side effects from pretty and logger

### LINKED ISSUE #650: tidy3d module import side effects
when importing tidy3 module there are two strange side effects that I don't really want and seem unnecessary

1. the stdout format changes. This causes plots to be duplicated, and makes it incompatible with other packages.
2. the logging level changes to everything so I can see logging even INFO messages

See this [notebook](https://gdsfactory.github.io/ubc/notebooks/11_sparameters.html)

I think is happening in the `__init__.py`
```
# make all stdout and errors pretty
pretty.install()
# traceback.install()
log.info(f"Using client version: {__version__}")
```

@tylerflex 
@momchil-flex

### PR DESCRIPTION
**Pull request by joamatab**
fixes #650

### CODE REVIEW

**Review by tylerflex — COMMENTED** [review]
I'm fine with this (removing `rich.pretty` and changing default log level to warning). Any concerns @momchil-flex ?

**Comment by tylerflex** [comment]
Note: @joamatab , could you reformat with 
```
black . --line-length 100
```
and push again?

**Comment by joamatab** [comment]
sure, just did that, 

you could add it as a pre-commit hook

similar to what we do in gdsfactory

**Comment by momchil-flex** [comment]
What does `rich.pretty` even do? I tried running a notebook without it and it seems exactly the same. I'm probably fine with removing it if you are @tylerflex 

Regarding the default logging level, I don't understand why just changing it to "warning" solves the underlying issue, which is that importing tidy3d interferes with the logger and may be undoing things that another package or the user have set. Also I'd rather keep it at info level by default if possible, unless this really solves the problem, but it doesn't seem to me like it does? Are there any alternatives? Something like optionally prevent tidy3d from tampering with the logger in its init?

**Comment by joamatab** [comment]
Yes, removing the changing of the default logger priority would be even better

**Comment by tylerflex** [comment]
I'm fine with removing the default logger priority if you are @momchil-flex. I agree with Joaquin that it's probably better to not set it when the package is imported. we should instead either manually set it as a user or adjust our log levels internally (ie from info -> warning) if we really think they should be seen.

**Comment by tylerflex** [comment]
@joamatab I made a PR #659  to remove rich.pretty() and the default log level completely, can you take a quick look and see if this fixes your issue and we can include in the patch. thanks.

**Comment by joamatab** [comment]
Looks good 👍 

Looking forward to the new release

**Pull request closed without merging**
