### PR TITLE
Cylinder side intersection visualization bug fix

### PR DESCRIPTION
**Pull request by weiliangjin2021**

### CODE REVIEW

**Review by lucas-flexcompute — APPROVED** [review]

**Comment by lucas-flexcompute** [comment]
@weiliangjin2021 I've added the fix for the tilted plane in this branch as well, since they are solving unrelated, but similar issues. Here's a preview of all settings working properly in both cases:

From your fix:
```python
_, ax = pyplot.subplots(6, 6, figsize=(12, 10), tight_layout=True)
ax = ax.reshape((-1,))
i = 0

for axis_num, axis in enumerate("xyz"):
    for angle in (0.1, -0.1, 0.6, -0.6):
        c = td.Cylinder(radius=0.51, length=2.02, axis=axis_num, sidewall_angle=angle)
        c.plot(x=0, ax=ax[i + 0])
        c.plot(y=0, ax=ax[i + 1])
        c.plot(z=0, ax=ax[i + 2])
        ax[i + 0].set_title("")
        ax[i + 1].set_title(f"Angle {angle}, {axis} axis")
        ax[i + 2].set_title("")
        i += 3
```
image

And mine (going through `intersections_tilted_plane` because of the transformation):
```python
_, ax = pyplot.subplots(6, 6, figsize=(12, 10), tight_layout=True)
ax = ax.reshape((-1,))
i = 0

for axis_num, axis in enumerate("xyz"):
    for angle in (0.1, -0.1, 0.6, -0.6):
        c = td.Cylinder(radius=0.51, length=2.02, axis=axis_num, sidewall_angle=angle).rotated(0, axis=axis_num)
        c.plot(x=0, ax=ax[i + 0])
        c.plot(y=0, ax=ax[i + 1])
        c.plot(z=0, ax=ax[i + 2])
        ax[i + 0].set_title("")
        ax[i + 1].set_title(f"Angle {angle}, {axis} axis")
        ax[i + 2].set_title("")
        i += 3
```
image

**Comment by momchil-flex** [comment]
Shall we merge @weiliangjin2021 ?

**Comment by momchil-flex** [comment]
Oh, please add a changelog item first.

**Comment by weiliangjin2021** [comment]
Looks good, thanks @lucas-flexcompute! I'll add update changelog now

**Comment by weiliangjin2021** [comment]
I think there is no need to squash. @momchil-flex feel free to merge if all look good to you.

**Pull request merged**
