### PR TITLE
load Tidy3dBaseModel objects without validation

### PR DESCRIPTION
**Pull request by tylerflex**
Added a `classmethod` called `Tidy3dBaseModel.load_without_validation(cls, **values) -> Tidy3dBaseModel`.
This is used as a constructor just like the regular init method, ie.

```py
box = td.Box.load_without_validation(size=(1,1,1))
```
but (as the name suggests) will not perform validation.

Use wisely!

### CODE REVIEW

**Comment by momchil-flex** [comment]
This seems almost working, but it's failing when I try to load from file (perhaps there's a way to do it properly?). I added a test to illustrate this, two reasons for the failure that I could find are that "Infinity" is not interpreted correctly, and arrays are not converted to tuples. Maybe this can be easily solved if I load the simulation string in a different way... or maybe it's a challenging limitation? I leave it up to you as you understand the mechanics much better.

**Comment by tylerflex** [comment]
ok, I'll look into it. The infinity part makes sense, we'd need to handle that separately (since it's part of the "validation").  The array part is a bit strange. Can you explain? There aren't any np.ndarrays in SIM_FULL.

**Comment by momchil-flex** [comment]
There are print statements in the failing test, the PolySlab vertices show up as tuples in the original simulation and as lists in the constructed one (not necessarily a problem; I don't know if it points to any potential problem though).

**Comment by tylerflex** [comment]
Hm ok. No not a problem. I can handle those edge cases directly. Thanks

**Comment by tylerflex** [comment]
Ok, this should be good to go @momchil-flex

**Comment by momchil-flex** [comment]
I found two more issues - again I've added this as part of the test:
  - Complex numbers don't seem to be constructed correctly
  - The second one is more abstruse: the constructed simulation errors when pickled. I can't exactly figure out what the problem is. The reason I stumbled upon this is because we use ProcessPoolExecutor on the backend, and it needs to pickle inputs. See if you have any idea...

Also I noticed you removed my previous IO test - I think it would have been good to keep it? However this has been rebased out here, and I reset hard my branch, so it may be lost for good (needs to be re-written).

**Comment by tylerflex** [comment]
> Also I noticed you removed my previous IO test - I think it would have been good to keep it? However this has been rebased out here, and I reset hard my branch, so it may be lost for good (needs to be re-written).

No, I just modified your test to make things more general.  Now what happens is we create 4 sim_dicts in 4 different ways, using these [functions](https://github.com/flexcompute/tidy3d/blob/88782f96fd66fb8d2279f66978e17bca1f3b54a6/tests/test_construct.py#L12-L35). The last of which is the case you added.

Then, these 4 dicts get put in a list and fed to `pytest.mark.parameterize()` which [feeds](https://github.com/flexcompute/tidy3d/blob/88782f96fd66fb8d2279f66978e17bca1f3b54a6/tests/test_construct.py#L74) them to each of the real tests. So there are now 2 tests x 4 sim_dicts loaded in different ways = 8 tests and we dont need to copy code for each of the tests.

**Comment by tylerflex** [comment]
Ok, I fixed the complex value case. The pickle thing is weird, I dont quite understand it. The two sims are `==` yet one is not pickle-able. From a bit of internet searching, it seems to be some quirk with pickle not being able to pickle things that are defined within a certain scope. For example

```py
import pickle

class A:
    pass

a = A()
pickle.dumps(a)
# works fine

def f():
    class B:
        pass
    b=b()
    pickle.dumps(b)
f()
# AttributeError: Can't pickle local object 'f.<locals>.B'
```

My thinking is that the error is because SIM_FULL and sim_constructed are defined in different scopes (sim_constructed is defined inside of the test function whereas SIM_FULL is defined in the global scope).

For some reason, this is becoming an issue when dealing with the constrained float types. For example
```py
permittivity float = pd.Field(
    1.0,
    ge=1.0,
    ...
)
```
if I comment out the `ge=1.0`, the error then moves to `tidy3d.components.geometry`. So it seems pickle just can't handle these constrained floats. So we could remove them and write them as separate validators, but then they dont show up in the schema and I think that hinders the UI efforts as it makes this information less available to the UI.

Last thing to note: `dill` is able to handle things as is. In the latest commit I
```py
import dill as pickle
```
and you can see the tests pass.

I might suggest seeing whether there are some options to run dill instead of pickle when pickling the subprocess commands? I'm not sure about the details there. I think it would be nice to retain the `ge=` and other constrained types if possible, so maybe there's a workaround regarding how the commands are run on the server. I dont think it's strictly a `load_without_validation` error (or at least anything that can be fixed by modifying that method).

**Comment by momchil-flex** [comment]
> The pickle thing is weird, I dont quite understand it. The two sims are `==` yet one is not pickle-able. 

Well for starters I think `==` is not real equality. What does it do exactly? Because the sims have been `==` ever since you first made this test, yet I've been discovering these real ways in which they differ. This is why I was hoping we can understand this pickling difference, because I'm wondering if it points to some hidden difference.

> My thinking is that the error is because SIM_FULL and sim_constructed are defined in different scopes (sim_constructed is defined inside of the test function whereas SIM_FULL is defined in the global scope).

On the backend, the sims are just loaded from file; either directly `from_file` or by `json.loads` the string and then construct without validation. Then the pickling error comes.

> 
> For some reason, this is becoming an issue when dealing with the constrained float types. For example
> 
> ```python
> permittivity float = pd.Field(
>     1.0,
>     ge=1.0,
>     ...
> )
> ```
> 
> if I comment out the `ge=1.0`, the error then moves to `tidy3d.components.geometry`. So it seems pickle just can't handle these constrained floats. So we could remove them and write them as separate validators, but then they dont show up in the schema and I think that hinders the UI efforts as it makes this information less available to the UI.
> 
> Last thing to note: `dill` is able to handle things as is. In the latest commit I
> 
> ```python
> import dill as pickle
> ```
> 
> and you can see the tests pass.
> 
> I might suggest seeing whether there are some options to run dill instead of pickle when pickling the subprocess commands? I'm not sure about the details there. I think it would be nice to retain the `ge=` and other constrained types if possible, so maybe there's a workaround regarding how the commands are run on the server. I dont think it's strictly a `load_without_validation` error (or at least anything that can be fixed by modifying that method). For example, see this solution https://stackoverflow.com/a/21345423/1483263

Yeah dill is one option around this, I'm pretty sure it can be incorporated. I'll look into it more though to see if I can understand this better before taking this approach.

**Comment by momchil-flex** [comment]
> > Also I noticed you removed my previous IO test - I think it would have been good to keep it? However this has been rebased out here, and I reset hard my branch, so it may be lost for good (needs to be re-written).
> 
> No, I just modified your test to make things more general. Now what happens is we create 4 sim_dicts in 4 different ways, using these [functions](https://github.com/flexcompute/tidy3d/blob/88782f96fd66fb8d2279f66978e17bca1f3b54a6/tests/test_construct.py#L12-L35). The last of which is the case you added.

Oh I see, thanks!

**Comment by tylerflex** [comment]
Oops, I edited your comment by mistake instead of making a new one.., anyway my response is below

> Well for starters I think == is not real equality. What does it do exactly? Because the sims have been == ever since you first made this test, yet I've been discovering these real ways in which they differ. This is why I was hoping we can understand this pickling difference, because I'm wondering if it points to some hidden difference.

All the dictionary contents should be identical if two sims are ==. if there's data involved, an additional check is that all the data arrays have all identical data and coords, so it's very much a "real" equality in that sense. However, these variables may be defined in different scope or handled in different ways internally by python as I allude to below and this seems to be the source of the error from what I can tell.

> My thinking is that the error is because SIM_FULL and sim_constructed are defined in different scopes (sim_constructed is defined inside of the test function whereas SIM_FULL is defined in the global scope).
On the backend, the sims are just loaded from file; either directly from_file or by json.loads the string and then construct without validation. Then the pickling error comes.

I'm a bit confused (although it doesn't really matter practically here), you load from file and then try to construct without 
validation? does that defeat the purpose?

> Yeah dill is one option around this, I'm pretty sure it can be incorporated. I'll look into it more though to see if I can understand this better before taking this approach.

Yea I guess check out the pathos package from that stackoverflow answer. From my tests I'm fairly confident it will solve this issue since it looks like just a clone of multiprocessing that uses dill instead of pickle and using dill.dumps() passes the tests you provided.

https://stackoverflow.com/a/21345423/1483263

**Comment by momchil-flex** [comment]
> Oops, I edited your comment by mistake instead of making a new one.., anyway my response is below

Yeah I've caught myself starting to d do this too sometimes...

> > Well for starters I think == is not real equality. What does it do exactly? Because the sims have been == ever since you first made this test, yet I've been discovering these real ways in which they differ. This is why I was hoping we can understand this pickling difference, because I'm wondering if it points to some hidden difference.
> 
> All the dictionary contents should be identical if two sims are ==. if there's data involved, an additional check is that all the data arrays have all identical data and coords, so it's very much a "real" equality in that sense. However, these variables may be defined in different scope or handled in different ways internally by python as I allude to in my previous response and this seems to be the source of the error from what I can tell.

Ah, I see, I think I was a bit confused about that (I thought the equality was not failing with the "Infinity" and complex problems, but I just tried and it is).

> > My thinking is that the error is because SIM_FULL and sim_constructed are defined in different scopes (sim_constructed is defined inside of the test function whereas SIM_FULL is defined in the global scope).
> > On the backend, the sims are just loaded from file; either directly from_file or by json.loads the string and then construct without validation. Then the pickling error comes.
> 
> I'm a bit confused (although it doesn't really matter practically here), you load from file and then try to construct without validation? does that defeat the purpose?

No I meant I replaced loading from file with construct without validation. But I meant the two ways seem to define the sim in exactly the same scope.
 
> > Yeah dill is one option around this, I'm pretty sure it can be incorporated. I'll look into it more though to see if I can understand this better before taking this approach.
> 
> Yea I guess check out the pathos package from that stackoverflow answer. From my tests I'm fairly confident it will solve this issue since it looks like just a clone of multiprocessing that uses dill instead of pickle and using dill.dumps() passes the tests you provided.
> 
> https://stackoverflow.com/a/21345423/1483263

Yeah I was looking at that yesterday, I think I'm OK with taking this approach if no other construct issues appear.

**Comment by momchil-flex** [comment]
OK pathos works on the backend. All tests but one are now passing. It turns out that complex poles in dispersive media still have the problem of not being properly converted after IO. I'm not sure why your complex number fix didn't apply there.

I've updated the test once again; I think you commented out the dispersive medium in `SIM_FULL` when doing the data restructuring. I've put this back in now and the construct test is failing because of the PoleResidue medium complex poles.

I swear this should be the last issue to fix. :)

**Comment by tylerflex** [comment]
Should be fixed now.

**Pull request merged**
