### PR TITLE
Only filter and merge in plot_structures_eps with transparency

### PR DESCRIPTION
**Pull request by tylerflex**
This makes it much faster for most cases, like `.plot()` with many structures

### CODE REVIEW

**Comment by tylerflex** [comment]
plotting `Simulation` with `sim.medium.permittivity=2` and structures with medium permittivity ranging from 1-3.

`plot()`
image
does not filter and merge

`plot_eps()` with no alpha:
image
does not filter and merge

`plot_eps()` with alpha:
image
filters and merges

**Comment by momchil-flex** [comment]
What's your thinking about `plot_field` eps overlays? Since monitors will usually only cover a subspace of the simulation that hopefully won't have way too many structure intersections, it's tempting to leave it on by default. And it already accepts an `eps_alpha` argument so it can be turned off if `eps_alpha=0`? I think the only thing to make sure then is that this indeed turns the overlay off, e.g. in `simulation.plot_structures_eps`, `if alpha == 0: return ax`

**Comment by tylerflex** [comment]
I dont think we can assume monitors cover subspaces that dont have too many structure intersections unfortunately.

But I dont think we have any other option but to still do the filtering and merging for overlays.

And yea if eps_alpha=0 we just dont call `simulation.plot_structures_eps()` (or we can do it if `alpha=0` in that function call too).

**Comment by momchil-flex** [comment]
I guess my question is simply should we then disable the overlay in field plotting by default?

**Pull request merged**
