### PR TITLE
Updates to help unify backend logging

### PR DESCRIPTION
**Pull request by momchil-flex**

### CODE REVIEW

**Comment by daquinteroflex** [comment]
Trying to fix the action situation fyi

**Review by lucas-flexcompute — APPROVED** [review]
I understand the changes required because of the backend log, so this looks fine. But thinking about the frontend only, is there any reason to use "USER" level instead of "INFO"? Or "SUPPORT" instead of "DEBUG"? I wonder if we should add a general comment for the future instructing frontend devs to only issue log messages using the standard levels, because that's what users would normally expect.

**Comment by daquinteroflex** [comment]
Many apologies for the notifications, I thought it was going to be an easy fix.

 I'm going to branch out and test in another PR, as I did try to reproduce this error in another personal PR and didn't get it. Will just clean up this PR and drop Momchil's specific commit on the other one that needs to be merged into pre/2.6

**Comment by daquinteroflex** [comment]
Oh my god! I'm so sorry! I don't know what I did

**Pull request closed without merging**
