### PR TITLE
Tyler/plotly app

### PR DESCRIPTION
**Pull request by tylerflex**
I think it could be good to merge this on so MC can work on integration.
corresponding notebook: https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/tyler/plotly_app/docs/source/notebooks/PlotlyApp.ipynb

### CODE REVIEW

**Comment by tylerflex** [comment]
Here's a notebook you can use for reference to test:
https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/tyler/plotly_app/docs/source/notebooks/PlotlyApp.ipynb

**Comment by momchil-flex** [comment]
Gave it a try. Some replies to you and some comments:

>   * Should 2 or 3 grid cells along a dimension cause that dimension to be ignored? (0D)

I think monitor.geometry.size being 0 along a specific dimension should cause it to be ignored.

>   * Just a line plot for 1D data?

That sounds right.

>   * For 2D data:
>     * line plot when the cross section axis is along one of the dimensions?
>     * or restrict to viewing the planar field data?

I would say just only give the planar data, without the option to choose a different cross-section.

>   * Same questions for how to handle single frequencies.

Is this w.r.t. a plot vs. f?

>   * Continuous slider bars vs discrete slider bars with positions only where data exists?  (same treatment for x,y,z,t,and f)?

If it performs fast enough, I don't see why not continuous.

>   * If restricting things, hide the UI components?

Don't understand.

Some comments:

- wondering if we can't have plotly and jupyter-dash as optional dependencies
- `# start up the app and it should pop up in your window` : it didn't pop up for me (chrome), and the hyperlink didn't work either, I had to copy the url in a new window.
- For small values of e.g. flux I'm getting some mu and n values on the tick labels. Is this supposed to mean 1e-6 and 1e-9, respectively? It may be confusing.
image
- Something's wrong with the simulation plotting in the y and z cross-sections. It's too wrong to even make sense pasting here. I'll send you the data file I was using and you can have a look (github doesn't let me attach hdf5)
- Equal aspect ratio in field plotting would be nice.

Overall it's really promising though!

**Review by shashwat-sh — COMMENTED** [review]
The app works great overall, I'd be pretty comfortable using it on a regular basis as a user.

- As Momchil may have already mentioned, it didn't pop up for me; I had to copy the URL into a new browser tab (Firefox). If this is browser-dependent, maybe you can display a message saying "if a window does not pop up, please copy and paste this URL into a new tab" or something.
- 
- Is it possible to allow changing the size of the figure? For example, in the attached image, the grating coupler's aspect ratio seems to force the figure size to be quite narrow. Would be useful if I could drag down the bottom edge to make the figure taller. Or maybe this happens because the monitor size is set to infinity (see second image) rather than the structure's aspect ratio.
image
image

- In some cases, axis labels are displayed with more decimal places than others (third attached image). This is very minor though, I was just wondering if it would be better to keep it consistent, or maybe to give the user the option of picking precision / scientific notation.
image

- This is very much a "nice to have in the future" thing, but it could be cool if the user can edit axis labels, titles, etc. to make "publication-ready" plots directly from the app. But maybe the the right way to do that is still directly through python...

**Comment by tylerflex** [comment]
I moved this to a new PR because things got messed up.  https://github.com/flexcompute/tidy3d/pull/295

**Comment by tylerflex** [comment]
closing this for now

**Pull request closed without merging**
