### PR TITLE
% Done Monitoring

### PR DESCRIPTION
**Pull request by tylerflex**
So this is looking pretty good on the front end, but needs some testing and a bit of refinement.

How it works now:
1. Use console.status (running man animation) to loop through pre-processing statuses.
2. Log that the solver is starting until we can successfully grab the % done data.
3. Progressbar through % done and print field_Decay in progress bar description.
4. Use console.status (running man animation) to loop through post-processing statuses

Simplifies a lot.
Job uses web.monitor() now.

Remaining issues:
* Takes a long time to start getting % done, by which point the task is already completed.   Need to either reduce this amount of time or change the message.
* Needs some more testing by us before I feel confident releasing it.

### CODE REVIEW

**Comment by tylerflex** [comment]
issue #140

**Comment by tylerflex** [comment]
Yea I think it marks the progress bar as "complete" when it's done running.  I dont know if it would be more confusing to leave like this or to change it to end at 32% (potentially making people think the job didn't finish).  What do you think?

**Comment by momchil-flex** [comment]
> Yea I think it marks the progress bar as "complete" when it's done running. I dont know if it would be more confusing to leave like this or to change it to end at 32% (potentially making people think the job didn't finish). What do you think?

I feel like given that this is the full output, it won't be confusing, and it would provide the extra information about at what point the shutoff happened.

image

**Comment by tylerflex** [comment]
Ok I pushed this fix.  If it's no longer running but the `perc_done < 100` it will just display the message about early shutoff and leave the progress bar where it was.  If it's no longer running but `perc_done >= 100` it will explicitly set the progress bar to "completed" like you see in all cases before this change.

**Comment by momchil-flex** [comment]
Oh, sorry, it does seem to print "success" twice

image

**Comment by momchil-flex** [comment]
Also, in old tidy3d, we do something like `status = "success" if status == "visualize"` and we don't print "visualize" as a status. This is because this step is the exporting of images (the three cross sections so far) on the server side, but the simulation data is already available to the user before this step is finished.

**Comment by tylerflex** [comment]
ok my last commit should do it, I refactored out the `get_status()` operation and made it return `success` if `visualize`.  Then, I fixed a minor bug where the shutoff message wasn't getting displayed in a weird edge case.  I also checked on a few notebooks that this works as expected.

**Pull request merged**
