### PR TITLE
Treating one edge case of intersect_side in PolySlab

### PR DESCRIPTION
**Pull request by weiliangjin2021**

### CODE REVIEW

**Review by tylerflex — CHANGES_REQUESTED** [review]
My only comment is that some of the conditionals are difficult to read.  Can we break them up a bit more?  I put specific comments.  @xin-flex  can you test the results look good?

**Comment by weiliangjin2021** [comment]
> My only comment is that some of the conditionals are difficult to read. Can we break them up a bit more? I put specific comments. @xin-flex can you test the results look good?

Somehow I don't see your specific comments?

**Comment by tylerflex** [comment]
test

**Comment by weiliangjin2021** [comment]
@tylerflex Please take a look again.

**Review by xin-flex — CHANGES_REQUESTED** [review]
image
I tested the same case, the two waveguides become symmetric, but they are now both cones instead of polyslab. Compare to another cross-section which renders correctly:
image

**Comment by tylerflex** [comment]
approve

**Review by tylerflex — APPROVED** [review]

**Review by xin-flex — APPROVED** [review]

**Pull request merged**
