### PR TITLE
better description for TimeMonitor.interval

### PR DESCRIPTION
**Pull request by tylerflex**
Requested by https://flow360.atlassian.net/browse/SCEM-2172

### CODE REVIEW

**Review by momchil-flex — APPROVED** [review]
This looks good, but while we're at it I wonder if we should change the default. People tend to have very big time monitors without realizing... But I'm not sure what's a good default setting. One thing could be the nyquist sampling rate used in the frequency monitors, which is on the order of 10-20 typically. But I don't think we want to not have a clear default (i.e. to be automatically reset by the simulation). Or do we? Or can we change defaults in some other way, e.g. not have start and stop time be beginning and end of the full simulation?

**Comment by tylerflex** [comment]
I don't think we should change defaults just because it will mess with people's existing scripts. 

One thing I could imagine though is setting the default value to `None` and warning in a validator that:
* we will set `interval` will be `1` by default.
* this can lead to a lot of data.
* if you really wanted this, to get rid of this warning explicitly set `interval=1` in your monitor.

**Comment by momchil-flex** [comment]
I think that sounds good! You wanna do this as part of this PR?

**Comment by tylerflex** [comment]
ok. what do you recommend for a good recommended `interval` value?

**Comment by momchil-flex** [comment]
I feel like maybe we shouldn't recommend a value; just print the warning if `interval=None` and also `start=0` and `stop=None` (the defaults). Just say that this may produce a lot of data, and consider using these arguments to reduce that.

**Pull request merged**
