### PR TITLE
pydantic.v1

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Comment by joamatab** [comment]
any updates on this Tyler?

**Comment by tylerflex** [comment]
Just back and forth with pylint and pydantic but nothing is getting resolved. Can see the issues here if you want to chime in:
* https://github.com/pydantic/pydantic/issues/6909
* https://github.com/pylint-dev/pylint/issues/8894

**Comment by tylerflex** [comment]
Because it's almost every file, so it basically renders pylint useless. I tried `pylint-pydantic` but it suffers from the same issue.

**Comment by joamatab** [comment]
how about don't run pylint until this gets resolved?

I've been using `ruff` and works great

**Comment by tylerflex** [comment]
wow, ruff is in fact quite great! I'll see what it looks like to integrate our workflow to ruff from pylint and will let you know.

**Comment by tylerflex** [comment]
tests are passing when using `ruff` so I think we'll go through with this once the other team gets a look at it!

**Comment by joamatab** [comment]
perfect, looking forward to a new release

our plan is to switch

1. tidy3d
2. meow
3. sax
4. gplugins

**Comment by joamatab** [comment]
any updates on this?

@tylerflex 
@momchil-flex
@lucas-flexcompute

**Comment by tylerflex** [comment]
Ok @lucas-flexcompute @momchil-flex this PR is ready to go. In summary:
* Updates pydantic requirements to 2.*
* Replaces all `pydantic` imports with `pydantic.v1`
* Removes `pylint`.
* Adds `ruff` with custom settings after some tweaking.
* Changes to all testing (tox,test_local)
* Runs the ruff formatter on the code and fixing various things here and there related to that.

Please take a look and let me know what you think. I think we can get this into the 2.4 release. @joamatab I guess if you have energy for it, you could let me know if you have any feedback as well! :)

**Comment by tylerflex** [comment]
@momchil-flex I guess we would still need
- [ ] update backend to pydantic 2.* and probably use ruff there as well.
- [ ] update internal and external reference on testing to use `ruff`.

**Review by lucas-flexcompute — APPROVED** [review]
Quite a lot of cleanup! I don't think I have anything else to add.

**Comment by tylerflex** [comment]
closing as this PR got stale and became a pain to merge, restarted in #1073

**Pull request closed without merging**
