### PR TITLE
Include material name in material_library's export_matlib_to_file

### PR DESCRIPTION
**Pull request by weiliangjin2021**
Requested by @jwang-magicloud to include material name info with a specific format in the generated json file.

### CODE REVIEW

**Review by tylerflex — APPROVED** [review]
Looks good to me. This file is not really used except by MC right? For example, not in our docs?

**Comment by tylerflex** [comment]
@weiliangjin2021 can you add a line in changelog's Changed section as well? Thanks. Note there might be some merge conflicts as of this morning so you may want to pull pre/1.10.0 branch locally first.

**Comment by weiliangjin2021** [comment]
> Looks good to me. This file is not really used except by MC right? For example, not in our docs?

That's correct, only by MC.

**Comment by weiliangjin2021** [comment]
> @weiliangjin2021 can you add a line in changelog's Changed section as well? Thanks. Note there might be some merge conflicts as of this morning so you may want to pull pre/1.10.0 branch locally first.

Added

**Review by jhmagicloud — APPROVED** [review]

**Pull request merged**
