### PR TITLE
added type field to dataarray in file

### PR DESCRIPTION
**Pull request by tylerflex**
Both hdf5 and json should have it now.

### CODE REVIEW

**Comment by momchil-flex** [comment]
This does not add the type tag to data arrays in `SimulationData`. It seems to me that the way it is set up now, it only adds it if you do something like `simulation.to_file("simulation.json", data_file="extra_data.hdf5")`, but not if you do e.g. `sim_data.to_file("sim_data.hdf5")`. I think the type tag handling needs to be moved to `_save_group_data` ?

**Comment by tylerflex** [comment]
ok, maybe I'm a bit unsure what we need then. so we want to add a type field to DataArray? like in Tidy3dBaseModel? (not just in the file?). Feel free to use this PR as a starting point if you have a clearer idea of what is required for the denormalizer.

**Comment by momchil-flex** [comment]
Yeah basically before the data reorg (before 1.6) the data arrays were also Tidy3dBaseModel and had the type field written in the simulation data hdf5. An was using this to define how the different data should be denormalized.

At the very minimum, we need to bring this back in the output of `sim_data.to_file("simulation_data.hdf5")`. It seem to me that the most straightforward way is if indeed data arrays just had a type tag like base models. However, I don't understand all the ins and outs of that (it seems like sometimes the lack of a type key in the dictionary may be used to differentiate base model from everything else, including a data array?), which is why I'd rather leave it to you or at least hear your input. Technically An can also work without this, but then he has to define in the denormalizer what types of DataArrays each of the MonitorData elements contain, which is not ideal (requires manual change if we change things on our side).

**Comment by momchil-flex** [comment]
The denormalizer actually works with the hdf5 file directly without using tidy3d frontend at all, currently.

**Pull request merged**
