### PR TITLE
Try gdspy vertices loading if gdstk loading fails

### PR DESCRIPTION
**Pull request by tylerflex**
And add gdspy and gdstk as optional requirements.

@lucas-flexcompute 
Just took a stab at this using (perhaps an abuse of) `try: except:`, but let me know if you think there's a better way to handle it.

I also notice that neither `gdstk` nor `gdspy` are actually required for these to work as they aren't imported in the main package. The user just supplies a `Cell` from either package. In that case, do we need them as optional requirements at all?

### CODE REVIEW

**Comment by momchil-flex** [comment]
Note that tests fail

**Comment by momchil-flex** [comment]
It's fine by me but it does seem like most of the code is duplicated between the two functions, would be nice to avoid that.

**Comment by tylerflex** [comment]
good catch, I rebased against pre/1.9.0 and then refactored to eliminate redundancy.

**Comment by lucas-flexcompute** [comment]
Sorry I'm late for the review… everything make sense, though. :+1:

**Comment by tylerflex** [comment]
@lucas-flexcompute I ended up doing the [method switching](https://github.com/flexcompute/tidy3d/blob/feature/optional_gds/tidy3d/components/geometry.py#L2091-L2108) based on the presence of `gdstk` or `gdspy` in `class(gds_cell.__class__)`. This was an attempt to avoid importing either package in tidy3d. But maybe this is not very future-proof, so if you have any other suggestions let us know. Not urgent as this seems to work for now.

**Pull request merged**
