### PR TITLE
Passing kwargs in Lorentz.from_nk

### PR DESCRIPTION
**Pull request by momchil-flex**
One last small thing noticed by MC...

### CODE REVIEW

**Review by tylerflex — APPROVED** [review]
looks good, maybe add kwargs to the docstring as well?

**Comment by momchil-flex** [comment]
Done, they were not present in the docstring of any of the methods... (this may be an omission we have in various other places)

**Comment by tylerflex** [comment]
I might be wrong but now it looks like the kwarg passing part of the code is no longer present?

**Review by tylerflex — APPROVED** [review]
I was wrong.  feel free to merge

**Pull request merged**
