### PR TITLE
Align configs.

### PR DESCRIPTION
**Pull request by an-li-the-dev**
This is a pr to align config.
* Remove credentials authentication
* Remove config.py, use envirnoment.py instead

### CODE REVIEW

**Review by tylerflex — CHANGES_REQUESTED** [review]
Thanks @an-li-the-dev 
I tried to set the environment to `dev` but got an error due to not being authorized. 

```py
from tidy3d.web.environment import Env, dev
Env.set_current(dev)

...

task_id = web.upload(sim, task_name="webAPI", verbose=verbose)
```
image


@momchil-flex @weiliangjin2021 do you know if there's any additional steps needed to run through Dev? or should it be the same authentication / API key?

**Comment by tylerflex** [comment]
Note: here is the dev environment
```
dev = EnvironmentConfig(
    name="dev",
    s3_region="us-east-1",
    web_api_endpoint="https://tidy3d-api.dev-simulation.cloud",
    website_endpoint="https://tidy3d.dev-simulation.cloud",
)
```

**Comment by an-li-the-dev** [comment]
``Env.dev.active()`` works for me, please try this syntax.

**Comment by tylerflex** [comment]
I still get the same error with this syntax.

**Comment by an-li-the-dev** [comment]
> I still get the same error with this syntax.

Did you change the API key? dev and prod's are not identical.

**Comment by tylerflex** [comment]
@weiliangjin2021 would you mind testing this PR (maybe on `WebAPI.ipynb` after setting the `Env.set_current(dev)`)? I can't seem to get my dev working properly. Thanks

**Review by tylerflex — APPROVED** [review]
pending successful test

**Comment by momchil-flex** [comment]
I'm actually working on something that requires dev config right now. Should I merge this in and start using it?

**Comment by weiliangjin2021** [comment]
It works for me after I manually update API keys in .tidy3d/config

**Comment by momchil-flex** [comment]
Oh I didn't realize this was merged into develop and not pre/2.3

@tylerflex I guess I'll merge develop in 2.3 again? Or should I revert the develop merge and only put it in 2.3?

**Comment by tylerflex** [comment]
Hm, maybe let's just merge develop into pre/2.3 again?

**Comment by momchil-flex** [comment]
Ok, there's a conflict though but I should be able to figure it out.

**Comment by momchil-flex** [comment]
Done.

**Pull request merged**
