### PR TITLE
Autograd <-> PyTorch wrapper

### LINKED ISSUE #1945: PyTorch (and maybe JAX) plugins for wrapping objective functions
We need some plugins to convert objective functions defined using autograd (since that is what we use) to PyTorch and possibly JAX. Proposed structure:
```
tidy3d/plugins
├── pytorch/
└── jax/
```

For JAX, we can probably just use [agjax](https://github.com/mfschubert/agjax)

### PR DESCRIPTION
**Pull request by yaugenst-flex**
@tylerflex fyi

### CODE REVIEW

**Review by tylerflex — APPROVED** [review]
Looks great, thanks for adding this.

So I guess this lets people write their objective function using autograd and then use PyTorch to optimize it? 

And I guess it would also work if they define some of their objective function using autograd and some in PyTorch?

```py
@to_torch
def get_data_ag(p):
    return web.run(get_sim(p))

def objective_pytorch(...):
    data = get_data_ag(p)
    return postprocess_pytorch(data)
```

Would it also work if I did something like
`run = to_torch(web.run)`
and use this as a drop in for web.run? to would it break I suppose since the simulation doesn't know how to store pytorch tensors?

**Comment by yaugenst-flex** [comment]
so mixing and matching is fine, but there is a tidy3d core that's autograd-only, which includes everything that concerns simulation definition as well as any post-processing that involves data-arrays or uses tidy3d internals (such as flux calculation or far field projection).
so the smallest "autograd core" would be something like
```python
@to_torch
def autograd_objective(params):
    sim = make_sim(params)
    sim_data = web.run(sim)
    # any code that calls tidy3d function on sim_data, for example:
    flux = sim_data["monitor"].flux
    return flux.values
```

but of course you could do custom field postprocessing in pytorch using field monitors if you return `sim_data["field_monitor"].Ex.values` for example

**Comment by yaugenst-flex** [comment]
essentially, the wrapped function needs to receive (at least some) pytorch tensors as input and return a pytorch tensor or scalar

**Comment by tylerflex** [comment]
cool thanks. eventually would be nice to get an example of this in some notebook. but feel free to merge for now!

**Pull request merged**
