### PR TITLE
Update `pre/2.8` to fix the sync docs action

### PR DESCRIPTION
**Pull request by daquinteroflex**
So the sync docs issue appeared to Marc in one of his pre/2.8 PRs per https://github.com/flexcompute/tidy3d/actions/runs/9990645191

So this is not urgent, but mainly of interest if we want  to see the live 2.8 branch docs at some point and also want that sync action error not to be raised in this branch. It was already fixed in `develop` so just involves propagating along to `pre/2.8`.

I guess most of the conflicts should be resolved in another commit from another PR into develop?

### CODE REVIEW

**Comment by momchil-flex** [comment]
Sorry is this basically a merge develop into pre/2.8 PR?

**Comment by daquinteroflex** [comment]
Yep, opened this because of the merge conflicts to have the reference and to reference a conflict resolution PR that fixes this if this is what we want to do?

**Comment by momchil-flex** [comment]
@tylerflex @yaugenst-flex we want to merge develop into pre/2.8 but there are a bunch of conflicts coming from autograd. Could one of you help resolve? It can be on this PR or you can start fresh.

**Comment by yaugenst-flex** [comment]
I think I'll have to do this in another PR since the branch here is just `develop`.

**Comment by momchil-flex** [comment]
Ah, right.

**Pull request closed without merging**
