### PR TITLE
small change in the documentation

### PR DESCRIPTION
**Pull request by FilipeFcp**
Hi @momchil-flex . Please let me know what you think when you have some time:

image

#1949

### CODE REVIEW

**Review by momchil-flex — APPROVED** [review]
Sounds great! Maybe also update the FAQ section a little?

**Comment by momchil-flex** [comment]
Actually, are you sure about the distinction from PlaneWave? Now that I think about it I'm a little confused about this, because the auxiliary simulation to the TFSF one just uses a PlaneWave. I thought that the difference is only in the area factor.

**Comment by FilipeFcp** [comment]
Hi Momchil. Yes, I understand that the difference is the area factor. A PlaneWave (infinity with periodic boundary) will inject 1 W of power. A TFSF will inject 1 $\frac{W}{\mu^2}$ intensity, or 1/sourceArea power.

Regarding the [FAQ](https://docs.flexcompute.com/projects/tidy3d/en/latest/faq/docs/faq/How-are-results-normalized.html), it is describing a `num_freq` attribute for the `SourceTime` object, that seems deprecated. Is the normalization still an issue for frequencies distant from the central one? Can I remove the reference for the `num_freq` attribute?

**Comment by momchil-flex** [comment]
> Hi Momchil. Yes, I understand that the difference is the area factor. A PlaneWave (infinity with periodic boundary) will inject 1 W of power. A TFSF will inject 1 W μ 2 intensity, or 1/sourceArea power.

What I was questioning was the statement about angled incidence. Is that really true? I thought that the normalization should not depend on the angle and the relationship between TFSF and PlaneWave should be the same at all angles.

> Regarding the [FAQ](https://docs.flexcompute.com/projects/tidy3d/en/latest/faq/docs/faq/How-are-results-normalized.html), it is describing a `num_freq` attribute for the `SourceTime` object, that seems deprecated. Is the normalization still an issue for frequencies distant from the central one? Can I remove the reference for the `num_freq` attribute?

I think this should be just `Source.num_freqs` instead of `SourceTime.num_freqs`. This argument is only available in ModeSource and Gaussian-type sources.

**Comment by FilipeFcp** [comment]
I think you are right. I just tested it and this is what I got for a plane wave:

deg flux
10 1.00007653,
20 1.00046873,
30 1.00205553
40 1.02323759
50 1.07655406

I believe the error for 40 and 50 is due to the fields taking too long to decay.

So I will change this part as well, and open another PR for the FAQ.

**Comment by momchil-flex** [comment]
Ah yeah I see, yeah PML are not great at absorbing oblique angles, you could try changing the normal direction boundaries to Absorber and put like 100 layers, might look better.

**Comment by FilipeFcp** [comment]
Hi @momchil-flex,

I ran some tests to fully understand this.

Yes, both the TFSF and Plane wave sources keep their quantities constant in the propagation direction (TFSF intensity and PW power). That information might be outdated, so I believe it's safe to remove it from the documentation and FAQ?

image



By the way, the absorber with many layers worked well for large incidence angles.

**Comment by momchil-flex** [comment]
Not sure what you mean? To me that information sounds correct still. The power is constant for a plane that is normal to the source injection axis (the axis normal to the source geometry) right? Meaning that the power in the propagation direction (the angled axis) would have an extra factor of 1 / cos(theta)?

**Comment by FilipeFcp** [comment]
Yes, this is correct. What I meant is that the same applies to both TFSF and PW. The TFSF docstring implies it would be different for a PW. I thought the FAQ had the same issue, but it's actually correct there.

**Comment by momchil-flex** [comment]
@FilipeFcp sorry is this ready for merge then?

**Comment by FilipeFcp** [comment]
Hi @momchil-flex. I believe it is.

**Pull request merged**
