### PR TITLE
Fix missing check in validator

### PR DESCRIPTION
**Pull request by lucas-flexcompute**

### CODE REVIEW

**Comment by tylerflex** [comment]
I wonder if the Union fields need
`discriminator=TYPE_TAG_STR`

?

**Comment by lucas-flexcompute** [comment]
I'm not sure. It seems to happen only on Windows.

**Comment by lucas-flexcompute** [comment]
> I wonder if the Union fields need `discriminator=TYPE_TAG_STR`

I think the unions cannot have a discriminator, because a list won't have a `type` attribute. That's the reason why I created the annotated medium type, so it could be used within the list.

**Comment by lucas-flexcompute** [comment]
The only test that is failing is the submodule. I've already updated it locally, but it doesn't seem to make any difference. @daquinteroflex @tylerflex any idea how to fix?

**Comment by tylerflex** [comment]
I think possibly your first Multilayer waveguide PR was failing submodules too, so pre/2.7 might be already out of date. Let me push a submodule update to pre/2.7 and see if it fixes things.

**Comment by tylerflex** [comment]
shoot, that didnt fix it maybe @daquinteroflex can take a look when he has time

**Comment by tylerflex** [comment]
before merging (once the submodule test is fixed) just a reminder to squash all of the commits into one if you dont mind.

**Review by tylerflex — APPROVED** [review]
Approve pending test passing and squashed commits.

Also curious what the issue was?

**Comment by lucas-flexcompute** [comment]
> Approve pending test passing and squashed commits.
> 
> Also curious what the issue was?

The problem was with `isinstance(..., MediumType)`. For some reason that doesn't work on Windows. So I replaced all checks with `isinstance(..., "some concrete type")`. I've also changed all instance validators to being root validators because I think that was also triggering the same issue internally.

**Comment by daquinteroflex** [comment]
Hello! Sorry about that, that's weird. I think I've fixed it now and for reference these are the commands I run to update it:

```raw
 1004  git checkout lucas/waveguide_plugin/test_fix
 1005  cd docs/
 1006  cd notebooks/
 1007  git pull origin pre/2.7 
 1008  cd ..
 1009  git add .
 1010  git commit -am ":wrench: Update submodule?"
 1011  git log
 1012  git push origin lucas/waveguide_plugin/test_fix 
 1013  history
```

**Pull request merged**
