### PR TITLE
Serializable `invdes` postprocessing

### LINKED ISSUE #1943: Integration of serializable expressions as post-processing option for `invdes`

### PR DESCRIPTION
**Pull request by yaugenst-flex**
Is this roughly what you had in mind @tylerflex?

This is branched off of #1848 
Closes #1943

### CODE REVIEW

**Comment by tylerflex** [comment]
Yea this is pretty much exactly what I had in mind.

**Comment by yaugenst-flex** [comment]
ok nice I'll fix the tests and wrap this up then

**Comment by tylerflex** [comment]
How would this work with InverseDesignMulti?

**Comment by yaugenst-flex** [comment]
yeah I have to check that. I _think_ it might just work? will test

**Comment by tylerflex** [comment]
Each simulation will need its own post process function. So i guess maybe a list of them is needed. But seems kind of clunky at first glance.

**Comment by yaugenst-flex** [comment]
how does this currently work? doesn't the `optimizer.run()` take only a single fn?

**Comment by tylerflex** [comment]
It does but the function takes the batch data as arguments (i think, it might also take the individual simulation data's as args too). Check the last couple cells of the main tutorial Invdes.ipynb (on mobile)

**Pull request merged**
