### PR TITLE
Lazily load `scipy.io` in `SimulationData.to_mat_file()`

### PR DESCRIPTION
**Pull request by yaugenst-flex**

### CODE REVIEW

**Review by momchil-flex — APPROVED** [review]
Thanks. No need for the changelog item since this feature has not yet been released, it is making its debut in 2.7.1.

**Comment by tylerflex** [comment]
@m-bone FYI. I didnt catch this, apparently scipy.io has a long import time so we're doing it only when the function is called now.

**Comment by yaugenst-flex** [comment]
image-mh

for reference

**Comment by m-bone** [comment]
Ah nice find that's a ridiculous load time just for this

**Pull request merged**
