### PR TITLE
Bump trimesh version to >=4,<4.2

### PR DESCRIPTION
**Pull request by caseyflex**
To restore compatibility with gdsfactory. Ran tests with `trimesh=4.0.0` and `trimesh=4.1.8`.

@daquinteroflex can you take a look at `poetry.lock`? Something isn't right, I ran `poetry update trimesh` but it also changed `python-versions` and `[package.extras]`.

@lucas-flexcompute can you take a look at the gds-related files to see if I missed anything?

### CODE REVIEW

**Comment by daquinteroflex** [comment]
Hi Casey, no worries, that looks about right! The [ pre v3 trimesh](https://github.com/mikedh/trimesh/blob/3.23.5/pyproject.toml) `pyproject.toml` didn't specify a minimum version, whereas [ the v4 does](https://github.com/mikedh/trimesh/blob/4.2.0/pyproject.toml) so poetry resolves this too. This applies too to the extras and so on. Also since the tests pass, and they run from the poetry environment, all is good!

**Comment by caseyflex** [comment]
> Hi Casey, no worries, that looks about right! The [ pre v3 trimesh](https://github.com/mikedh/trimesh/blob/3.23.5/pyproject.toml) `pyproject.toml` didn't specify a minimum version, whereas [ the v4 does](https://github.com/mikedh/trimesh/blob/4.2.0/pyproject.toml) so poetry resolves this too. This applies too to the extras and so on. Also since the tests pass, and they run from the poetry environment, all is good!

Nice, thanks for checking!

**Review by daquinteroflex — APPROVED** [review]

**Comment by tylerflex** [comment]
Hey @caseyflex could you update the submodule commit. for `docs/faq` for this? It's currently failing
```
Checking docs/faq for updates...
Error: Submodule docs/faq is not up to date. Please update it.
```

**Comment by caseyflex** [comment]
> Hey @caseyflex could you update the submodule commit. for `docs/faq` for this? It's currently failing
> 
> ```
> Checking docs/faq for updates...
> Error: Submodule docs/faq is not up to date. Please update it.
> ```

done!

**Pull request merged**
