### PR TITLE
:books: Include mode web api docs

### PR DESCRIPTION
**Pull request by daquinteroflex**
Hi, included the API for mode simulations as per this https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/web/api/mode.py requested by Alec.

### CODE REVIEW

**Comment by daquinteroflex** [comment]
Screenshot from 2024-08-07 11-36-30

**Comment by tylerflex** [comment]
looks good to me. thanks Dario. Just wondering why MODE is in all caps?

**Comment by tylerflex** [comment]
might prefer just Mode Solver Web API

**Review by alec-flexcompute — APPROVED** [review]
Looks great, thanks!

**Comment by daquinteroflex** [comment]
Sounds good I've updated it. 

I guess I'm still ingrained subconsciously the MODE, CHARGE naming of Lumerical tools haha.

**Review by tylerflex — APPROVED** [review]
Looks good, sorry I didnt see this earlier!

**Comment by tylerflex** [comment]
@daquinteroflex should we merge this once the notebook submodule is fixed?

**Comment by daquinteroflex** [comment]
Hello, sorry this passed me, I will merge as soon as the tests pass!

**Pull request merged**
