### PR TITLE
Replace gdspy with gdstk in GDSII import and tests

### PR DESCRIPTION
**Pull request by lucas-flexcompute**
Minor improvement in `PolySlab.from_gds` by letting `gdstk` take care of filtering and scaling when possible.

Removed a few gdspy imports that were not being used.

Signed-off-by: Lucas Heitzmann Gabrielli <lucas@flexcompute.com>

### CODE REVIEW

**Comment by joamatab** [comment]
This is great and will remove the gdspy depedency, which is hard to install without conda

**Review by tylerflex — APPROVED** [review]
Looks good to me. Thanks @lucas-flexcompute !

**Comment by tylerflex** [comment]
Hey @lucas-flexcompute I'm going to merge this into develop after all, so it can go into 1.8.2. If you get a chance, can you rebase against `develop`? after that, let me know and I will merge it in. Thanks!

**Comment by lucas-flexcompute** [comment]
Done!

**Pull request merged**
