### PR TITLE
set rich < 12.6.0 to fix double progressbars

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Comment by momchil-flex** [comment]
Maybe just rich<13.0 or something?

**Comment by tylerflex** [comment]
This was the latest version that didn't display the double progress bars. 12.6.0 did.

**Comment by momchil-flex** [comment]
Oh I see. So <12.6.0 then?

**Comment by tylerflex** [comment]
I wasn't sure you could do that, it didn't work with pip, let's see if the tests work.

**Pull request merged**
