### PR TITLE
Stricter Tests

### PR DESCRIPTION
**Pull request by tylerflex**
Tox tests now check for
* clean lint.
* clean diff from black

Blacked code using updated black, adds spacing around `**`

### CODE REVIEW

**Comment by momchil-flex** [comment]
So we gotta make sure everyone is using the same - or at least somewhat consistent - version of black? We should not this down somewhere explicitly.

**Comment by tylerflex** [comment]
https://github.com/flexcompute/tidy3d/blob/tyler/strict_tests/tests/requirements.txt#L2

**Comment by momchil-flex** [comment]
Seems like the checks don't pass?

**Comment by momchil-flex** [comment]
I think the only reason they don't pass is because of this `tidy3d/components/monitor.py:159:18: W0612: Unused variable 'tind_end' (unused-variable)`.

**Comment by tylerflex** [comment]
yea this is a typo.  Let me fix and see if the tests run again

**Pull request merged**
