### PR TITLE
Alec/remove converter

### PR DESCRIPTION
**Pull request by alec-flexcompute**

### CODE REVIEW

**Review by tylerflex — COMMENTED** [review]
Looks good. can we just squash these into a single commit please? and also merge into pre/2.7? thanks!

**Comment by alec-flexcompute** [comment]
So I'm not authorized to merge this PR. Could I grab access? Then I'll do the squash-and-merge

**Comment by tylerflex** [comment]
You'll need to rebase locally against pre/2.7 and then squash the commits there. You can change `pick` to `fixup` in the commit list for the bottom N-1 commits and it should work.

**Comment by alec-flexcompute** [comment]
Gotcha, yeah I just realized that there's gonna be conflicts with this
method

**Review by tylerflex — APPROVED** [review]

**Comment by tylerflex** [comment]
I decided to add a CHANGELOG, and make the old command just error with a link to your new repo. Also added a test to ensure it worked properly.

Occurred to me after the fact that we should do this, just in case people are confused by it disappearing. Will merge once tests pass.

**Pull request merged**
