### PR TITLE
run updated black

### PR DESCRIPTION
**Pull request by tylerflex**
Also upgrades black version to 23.12.1

### CODE REVIEW

**Comment by tylerflex** [comment]
We can worry about this after the break

**Comment by daquinteroflex** [comment]
What do you think was wrong with it? Seems like it ran fine?

**Comment by tylerflex** [comment]
So I
* upgraded my black to `23.12.1`
* ran black
* updated black version in pyproject.toml
* ran poetry lock
but then I think the tests failed. Maybe this was because the tests run from pre/2.6?

**Comment by tylerflex** [comment]
Huh, now that I look at it thought, the tests passed. Not sure what was going on, then. I might have misunderstood something.

**Comment by daquinteroflex** [comment]
Ahh that test that didn't pass seems like it was a black reformatting test you did in the working commit (maybe through the precommit?), and I suspect maybe after you ran again it worked?

**Pull request closed without merging**
