### PR TITLE
supports upload task with gz

### PR DESCRIPTION
**Pull request by magiWei**

### CODE REVIEW

**Comment by lucas-flexcompute** [comment]
Currently, we only use hdf5 when there are custom datasets in the simulation, otherwise we upload the json version. With this change, we'll always use a compressed hdf5, is that correct? Are there any downsides to this option?

Other than that, the use of `os.system` to call gzip/gunzip is non-portable. It's better to use the [gzip](https://docs.python.org/3/library/gzip.html) module.

**Comment by tylerflex** [comment]
> Currently, we only use hdf5 when there are custom datasets in the simulation, otherwise we upload the json version. With this change, we'll always use a compressed hdf5, is that correct? Are there any downsides to this option?

I forget why we decided to upload the json if no data was present (instead of just all hdf5). There must have been some reason, maybe @momchil-flex remembers.

Anyway, what is the main advantage of this PR? I'm reluctant to make potentially breaking changes to the webapi so want to make sure it is worth changing things. Also I think it would be helpful for @lei-flex to take a look because I'm not sure how this affects our backend pipeline

**Comment by momchil-flex** [comment]
GUI is transitioning to working with `hdf5.gz` files so they can support custom data, and we can do the same here. The reason we used to upload `.json` files was for GUI.

We need to remove or modify the `download_json` and `download_hdf5` functions. https://github.com/flexcompute/tidy3d/blob/d121071745ed7d13dae145eee359d8de72174713/tidy3d/web/webapi.py#L464-L513

Modifying would mean e.g. trying to download the file directly, and if failing trying to donwload the `hdf5.gz` file and then repackaging as json or hdf5.

Currently the mode solver does not support hdf5.gz. In general I think we will wait a little with merging this PR.

**Comment by magiWei** [comment]
> GUI is transitioning to working with `hdf5.gz` files so they can support custom data, and we can do the same here. The reason we used to upload `.json` files was for GUI.
> 
> We need to remove or modify the `download_json` and `download_hdf5` functions.
> 
> https://github.com/flexcompute/tidy3d/blob/d121071745ed7d13dae145eee359d8de72174713/tidy3d/web/webapi.py#L464-L513
> 
> Modifying would mean e.g. trying to download the file directly, and if failing trying to donwload the `hdf5.gz` file and then repackaging as json or hdf5.
> 
> Currently the mode solver does not support hdf5.gz. In general I think we will wait a little with merging this PR.

`download_json` function has removed. Can the original versions download reslult.hdf5  and  download simulation.hdf5 source file through `download_hdf5` function? if so, need to change the `download_hdf5` logic.

**Comment by momchil-flex** [comment]
> `download_json` function has removed. Can the original versions download reslult.hdf5 and download simulation.hdf5 source file through `download_hdf5` function? if so, need to change the `download_hdf5` logic.

Actually, looking at the code again, I propose something else: modifying `SimulationTask.get_simulation.json` and `SimulationTask.get_simulation_hdf5` to download the `hdf5.gz` file. Then, `SimulationTask.get_simulation_hdf5` can just unzip that to the provided `path`.  `SimulationTask.get_simulation_json` will need to unzip it to a temporary `hdf5` file, then read the json string from that file and write it to the provided `path`. This also won't break backwards compatibility for users who may be using the `download_json` and `download_hdf5` web functions.

Note that there are two pylint errors in the tests. The one about protected access can be avoided by placing a comment `# pylint:disable=protected-access` on that line or right above it.

**Comment by magiWei** [comment]
> propose



> > `download_json` function has removed. Can the original versions download reslult.hdf5 and download simulation.hdf5 source file through `download_hdf5` function? if so, need to change the `download_hdf5` logic.
> 
> Actually, looking at the code again, I propose something else: modifying `SimulationTask.get_simulation.json` and `SimulationTask.get_simulation_hdf5` to download the `hdf5.gz` file. Then, `SimulationTask.get_simulation_hdf5` can just unzip that to the provided `path`. `SimulationTask.get_simulation_json` will need to unzip it to a temporary `hdf5` file, then read the json string from that file and write it to the provided `path`. This also won't break backwards compatibility for users who may be using the `download_json` and `download_hdf5` web functions.
> 
> Note that there are two pylint errors in the tests. The one about protected access can be avoided by placing a comment `# pylint:disable=protected-access` on that line or right above it.

`@wait_for_connection 
 def download_json( 
     task_id: TaskId, 
     path: str = SIM_FILE_JSON, 
     verbose: bool = True, 
     progress_callback: Callable[[float], None] = None, 
 ) -> None: 
     """Download the `.json` file associated with the :class:`.Simulation` of a given task. 
  
     Parameters 
     ---------- 
     task_id : str 
         Unique identifier of task on server.  Returned by :meth:`upload`. 
     path : str = "simulation.json" 
         Download path to .json file of simulation (including filename). 
     verbose : bool = True 
         If `True`, will print progressbars and status, otherwise, will run silently. 
     progress_callback : Callable[[float], None] = None 
         Optional callback function called when downloading file with ``bytes_in_chunk`` as argument. 
  
     """ 
  
     task = SimulationTask(taskId=task_id) 
     task.get_simulation_json(path, verbose=verbose, progress_callback=progress_callback) 
  
  
 @wait_for_connection 
 def download_hdf5( 
     task_id: TaskId, 
     path: str = SIM_FILE_HDF5, 
     verbose: bool = True, 
     progress_callback: Callable[[float], None] = None, 
 ) -> None: 
     """Download the `.hdf5` file associated with the :class:`.Simulation` of a given task. 
  
     Parameters 
     ---------- 
     task_id : str 
         Unique identifier of task on server.  Returned by :meth:`upload`. 
     path : str = "simulation.hdf5" 
         Download path to .hdf5 file of simulation (including filename). 
     verbose : bool = True 
         If `True`, will print progressbars and status, otherwise, will run silently. 
     progress_callback : Callable[[float], None] = None 
         Optional callback function called when downloading file with ``bytes_in_chunk`` as argument. 
  
     """ 
  
     task = SimulationTask(taskId=task_id) 
     task.get_simulation_hdf5(path, verbose=verbose, progress_callback=progress_callback) `

`SimulationTask.get_simulation_hdf5` is just for downloading the output/monitor_data.hdf5 result file, so it no need to change.

` SimulationTask.get_simulation_json` will need to unzip it to a temporary hdf5 file, then read the json string from that file and write it to the provided path

**Comment by magiWei** [comment]
> > `download_json` function has removed. Can the original versions download reslult.hdf5 and download simulation.hdf5 source file through `download_hdf5` function? if so, need to change the `download_hdf5` logic.
> 
> Actually, looking at the code again, I propose something else: modifying `SimulationTask.get_simulation.json` and `SimulationTask.get_simulation_hdf5` to download the `hdf5.gz` file. Then, `SimulationTask.get_simulation_hdf5` can just unzip that to the provided `path`. `SimulationTask.get_simulation_json` will need to unzip it to a temporary `hdf5` file, then read the json string from that file and write it to the provided `path`. This also won't break backwards compatibility for users who may be using the `download_json` and `download_hdf5` web functions.
> 
> Note that there are two pylint errors in the tests. The one about protected access can be avoided by placing a comment `# pylint:disable=protected-access` on that line or right above it.

`SimulationTask.get_simulation_hdf5` is just for downloading the output/monitor_data.hdf5 result file, so it no need to change.

 `SimulationTask.get_simulation_json` will need to unzip it to a temporary hdf5 file, then read the json string from that file and write it to the provided path

**Comment by momchil-flex** [comment]
Ok, actually I see that there is a bit of a mess that needs to be cleaned up. There are two different HDF5 files. The `simulation.hdf5` that defines the initial simulation, and the `simulation_data.hdf5` (called `output/monitor_data.hdf5` on the server) that contains the results. The `SimulationTask.get_simulation_hdf5` gets the *monitor data* file indeed. This method is used in both `webapi.load` and in `webapi.download_hdf5`. The second of those methods sounds like it should be downloading `simulation.hdf5`, but it is downloading the data file instead. As part of this PR, I think what we need to do is fix `webapi.download_hdf5` to return `simulation.hdf5` and make sure that `webapi.download_json` can also get the `simulation.json` successfully.

@magiWei I can help take care of this part once SimulationTask is updated properly. However, I think some changes are still needed there. Currently, it seems that you continue to upload both a `simulation.json` and a `simulation.hdf5.gz`, and the json file is only uploaded so that it can be downloaded later on. This doesn't make much sense. Instead we should change things to:
- Only upload `simulation.hdf5.gz`, do not upload `simulation.json`
- Change `SimulationTask.get_simulation_hdf5` to download `SIM_FILE_HDF5_GZ` and unzip it
- Rename the current `SimulationTask.get_simulation_hdf5` to `SimulationTask.get_sim_data_hdf5` and use that in `webapi.download` but *not* in `webapi.download_hdf5`
- Change SimulationTask.get_simulation_json to call `SimulationTask.get_simulation_hdf5`, then load the json from the hdf5 file
- Change SimulationTask.get_simulation to call `SimulationTask.get_simulation_hdf5` and load the simulation from the hdf5 file directly, not from json.

**Comment by magiWei** [comment]
> Ok, actually I see that there is a bit of a mess that needs to be cleaned up. There are two different HDF5 files. The `simulation.hdf5` that defines the initial simulation, and the `simulation_data.hdf5` (called `output/monitor_data.hdf5` on the server) that contains the results. The `SimulationTask.get_simulation_hdf5` gets the _monitor data_ file indeed. This method is used in both `webapi.load` and in `webapi.download_hdf5`. The second of those methods sounds like it should be downloading `simulation.hdf5`, but it is downloading the data file instead. As part of this PR, I think what we need to do is fix `webapi.download_hdf5` to return `simulation.hdf5` and make sure that `webapi.download_json` can also get the `simulation.json` successfully.
> 
> @magiWei I can help take care of this part once SimulationTask is updated properly. However, I think some changes are still needed there. Currently, it seems that you continue to upload both a `simulation.json` and a `simulation.hdf5.gz`, and the json file is only uploaded so that it can be downloaded later on. This doesn't make much sense. Instead we should change things to:
> 
> * Only upload `simulation.hdf5.gz`, do not upload `simulation.json`
> * Change `SimulationTask.get_simulation_hdf5` to download `SIM_FILE_HDF5_GZ` and unzip it
> * Rename the current `SimulationTask.get_simulation_hdf5` to `SimulationTask.get_sim_data_hdf5` and use that in `webapi.download` but _not_ in `webapi.download_hdf5`
> * Change SimulationTask.get_simulation_json to call `SimulationTask.get_simulation_hdf5`, then load the json from the hdf5 file
> * Change SimulationTask.get_simulation to call `SimulationTask.get_simulation_hdf5` and load the simulation from the hdf5 file directly, not from json.
> 
> Does that make sense?

Changed！And there is a unit test failure, I don't know the specific reason, can you help fix it?

**Comment by tylerflex** [comment]
Hi @magiWei , the failing unit tests was from our jax updating and breaking things. I fixed it in #1038 and will release a patch 2.3.3. I started up the tests for this PR and they should be passing now.

**Comment by tylerflex** [comment]
Looks like tests fail but this time due to a gzip related thing:
```
tests/test_web/test_tidy3d_task.py ..F......                             [100%]
[7624](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7625)
  
[7625](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7626)
  =================================== FAILURES ===================================
[7626](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7627)
  ___________________________ test_get_simulation_json ___________________________
[7627](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7628)
  
[7628](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7629)
  monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f8df3581910>
[7629](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7630)
  set_api_key = None
[7630](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7631)
  
[7631](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7632)
      @responses.activate
[7632](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7633)
      def test_get_simulation_json(monkeypatch, set_api_key):
[7633](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7634)
          def mock_download(*args, **kwargs):
[7634](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7635)
              file_path = kwargs["to_file"]
[7635](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7636)
              with open(file_path, "w") as f:
[7636](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7637)
                  f.write("test data")
[7637](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7638)
      
[7638](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7639)
          monkeypatch.setattr("tidy3d.web.simulation_task.download_file", mock_download)
[7639](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7640)
      
[7640](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7641)
          responses.add(
[7641](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7642)
              responses.GET,
[7642](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7643)
              f"{Env.current.web_api_endpoint}/tidy3d/tasks/3eb06d16-208b-487b-864b-e9b1d3e010a7/detail",
[7643](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7644)
              json={
[7644](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7645)
                  "data": {
[7645](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7646)
                      "taskId": "3eb06d16-208b-487b-864b-e9b1d3e010a7",
[7646](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7647)
                      "createdAt": "2022-01-01T00:00:00.000Z",
[7647](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7648)
                  }
[7648](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7649)
              },
[7649](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7650)
              status=200,
[7650](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7651)
          )
[7651](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7652)
          task = SimulationTask.get("3eb06d16-208b-487b-864b-e9b1d3e010a7")
[7652](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7653)
          JSON_NAME = "tests/tmp/task.json"
[7653](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7654)
          with open(JSON_NAME, "w") as f:
[7654](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7655)
  >           task.get_simulation_json(JSON_NAME)
[7655](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7656)
  
[7656](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7657)
  tests/test_web/test_tidy3d_task.py:107: 
[7657](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7658)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[7658](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7659)
  tidy3d/web/simulation_task.py:321: in get_simulation_json
[7659](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7660)
      self.get_simulation_hdf5(SIM_FILE_HDF5)
[7660](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7661)
  tidy3d/web/simulation_task.py:539: in get_simulation_hdf5
[7661](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7662)
      extract_gz_file(SIM_FILE_HDF5_GZ, to_file)
[7662](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7663)
  tidy3d/web/file_util.py:33: in extract_gz_file
[7663](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7664)
      f_out.write(f_in.read())
[7664](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7665)
  /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/gzip.py:300: in read
[7665](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7666)
      return self._buffer.read(size)
[7666](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7667)
  /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/gzip.py:487: in read
[7667](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7668)
      if not self._read_gzip_header():
[7668](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7669)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[7669](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7670)
  
[7670](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7671)
  self = <gzip._GzipReader object at 0x7f8df352ddc0>
[7671](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7672)
  
[7672](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7673)
      def _read_gzip_header(self):
[7673](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7674)
          magic = self._fp.read(2)
[7674](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7675)
          if magic == b'':
[7675](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7676)
              return False
[7676](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7677)
      
[7677](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7678)
          if magic != b'\037\213':
[7678](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7679)
  >           raise BadGzipFile('Not a gzipped file (%r)' % magic)
[7679](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7680)
  E           gzip.BadGzipFile: Not a gzipped file (b'te')
[7680](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7681)
  
[7681](https://github.com/flexcompute/tidy3d/actions/runs/5688240414/job/15436487914?pr=999#step:5:7682)
  /opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/gzip.py:435: BadGzipFile
```

**Comment by magiWei** [comment]
> Looks like tests fail but this time due to an issue related to this PR

Fixed.

**Comment by momchil-flex** [comment]
Thanks @magiWei I think this looks good now. I will just make a few cosmetic changes before merging (next week).

**Comment by momchil-flex** [comment]
@tylerflex this is the last frontend PR apart from the pydantic one. I rebased it and fixed eveyrthing up as it was somewhat stale, and tested and it seems to work. Note that with this, hdf5.gz will always be uploaded instead of json/hdf5. The solver already supports that and GUI team is working on supporting this when they switch to 2.4.

The one thing I'm wondering about is these types of statements where a regular "print" is used. https://github.com/flexcompute/tidy3d/pull/999/files#diff-9ef8b43458a5c52262aae2f54d04b0ca7d2f8e141fded282948a9f2413cc3f80R328-R329

Is this handled correctly or should it be some sort of e.g. console.log?

**Comment by tylerflex** [comment]
It should be like this
https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/web/webapi.py#L187-L189

```
console = rich.Console()
console.log("message")
```

**Pull request merged**
