### PR TITLE
force progress bars to 100% when task completed

### PR DESCRIPTION
**Pull request by tylerflex**
Tested on WebApi.ipynb notebook and works as expected.

### CODE REVIEW

**Review by lucas-flexcompute — COMMENTED** [review]
Looks good to me! I'm much happier with my progress bars actually finishing now! :+1:

I have 3 comments:

- All my widgets appear in duplicates. Is that a problem on my side?

- The field decay bar did not reach 100% (probably due to early shut off). Do we want to change that as well?

```[16:48:28] INFO     running solver                                                                    [webapi.py](file:///home/lucas/Flexcompute/dev/tidy3d/tidy3d/web/webapi.py):[284](file:///home/lucas/Flexcompute/dev/tidy3d/tidy3d/web/webapi.py#284)
% done (field decay = 7.78e-08) ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   8% -:--:--
% done (field decay = 7.78e-08) ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   8% -:--:--
[16:48:51] INFO     early shutoff detected, exiting.                                                  [webapi.py](file:///home/lucas/Flexcompute/dev/tidy3d/tidy3d/web/webapi.py):[295](file:///home/lucas/Flexcompute/dev/tidy3d/tidy3d/web/webapi.py#295)
```

- Just to note: I'm on a freshly-installed system and `rich` complained about not having `ipywidgets` installed. It's not a hard requirement, but the progress bars are not displayed in that case.

**Comment by tylerflex** [comment]
Thanks for the review, Lucas

> All my widgets appear in duplicates. Is that a problem on my side?
> I'm on a freshly-installed system and rich complained about not having ipywidgets installed. It's not a hard requirement, but the progress bars are not displayed in that case.

I think it's a problem with rich, maybe you found the solution in installing ipywidgets? Should we add it as a requirement?

> The field decay bar did not reach 100% (probably due to early shut off). Do we want to change that as well?

Yea, this is desired behavior I think but I could see the argument for completing the progress bar even with early shutoff. What do you think? Maybe @momchil-flex has an opinion on it too?

**Comment by lucas-flexcompute** [comment]
> I think it's a problem with rich, maybe you found the solution in installing ipywidgets? Should we add it as a requirement?

No, without ipywidgets there are no bars whatsoever; with it, I get 2. It could be related to Jupyter's automatic display (similar to issuing a print and returning an object as the last line in a cell: we see the result of the print and a representation of the object that Jupyter creates automatically.

> Yea, this is desired behavior I think but I could see the argument for completing the progress bar even with early shutoff. What do you think? Maybe @momchil-flex has an opinion on it too?

I'd prefer to have the bar finish at 100% unless the simulation was interrupted due to some sort of error, which is not the case. Currently, it looks like something went wrong and the simulation did not complete, when, in reality, it actually finished earlier and successfully.

**Comment by tylerflex** [comment]
The double progress bar thing is a known issue. Here's an [issue](https://github.com/Textualize/rich/issues/1888) I made on rich about it.

Ok, I can change the early shutoff behavior in a couple hours. thanks.

**Comment by tylerflex** [comment]
k, made the change, should update to 100% assuming the task succeeds

**Review by lucas-flexcompute — APPROVED** [review]

**Pull request merged**
