### PR TITLE
The big documentation and development upgrade

### PR DESCRIPTION
**Pull request by daquinteroflex**
This is the one we will merge whenever we want to. I am only perfecting things at this point.

Supersedes all others as they are so coupled changes and are hard to break down into smaller bits eg. https://github.com/flexcompute/tidy3d/pull/1238

First stage implementation of https://github.com/flexcompute/tidy3d/issues/1148

Could I propose maybe we do this merge independently of 2.6 but before 2.6? Or the documentation upgrade becomes 2.6 and the further upgrades become 2.7?

I just realised I should open this only when pre/2.6 branch is open and maybe only when 2.5 is fully done? Seems like an easy base change whenever we decide.

### CODE REVIEW

**Comment by tylerflex** [comment]
Thanks @daquintero. What I was imagining was something like this. Let me know if it makes sense to you or it complicates things. I dont have a strong opinion, just was under this impression:

* We just released 2.5.0rc3.
* Pretty soon, we will merge `pre/2.6` into `develop` and release `2.6.0`.
* Then we merge this PR into develop (which will look a lot like current `pre/2.6`)
* Then we can release 2.6.0rc1 and start testing with the new docs synced to `tidy3d-docs-demo`?

Or is this different from the plan you had in mind? If we go this route, the best will be to rebase against the pre/2.6 branch I think.

**Comment by tylerflex** [comment]
Sorry i meant pre/2.5

**Comment by daquinteroflex** [comment]
As of the current setup it gets live updated from this branch on this webside: https://flexcompute-tidy3d-docs-demo.readthedocs-hosted.com/en/repo_merge_no_history/

**Comment by daquinteroflex** [comment]
Because rebasing was very painful upgrading from here https://github.com/flexcompute/tidy3d/pull/1319

**Pull request closed without merging**
