### PR TITLE
verbose option in webapi

### PR DESCRIPTION
**Pull request by flexcompute-readthedocs**
`web.run(..., verbose=False)`
`web.upload(..., verbose=False)` (etc)
`job = Job(..., verbose=False)`
`batch = Batch(..., verbose=False)`

leads to no output unless warning or error.

### CODE REVIEW

**Comment by tylerflex** [comment]
I will rebase this soon

**Comment by tylerflex** [comment]
ok @lucas-flexcompute this is working again, when you get a chance, could you do a sanity check? [Here's](https://github.com/flexcompute-readthedocs/tidy3d-docs/blob/tyler/remove_rich/docs/source/notebooks/WebAPI.ipynb) a file that tests all of the webapi functions with the verbose option switchable. Thank you!

**Review by lucas-flexcompute — COMMENTED** [review]
It all seems pretty good to me, except `BatchResults`, wich still shows a download progress bar. Could it inherit the `verbose` attribute from `web.Batch` when created from the `run` call?

I don't know if you're changing the notebook as well, but if you are, there's a space missing after the last comma in
```python
job = web.Job(simulation=sim, task_name="job",verbose=verbose)
```
and the import statement
```python
import tidy3d.web as web
```
should probably be in the first cell, so that the user can run the batch example without running the job one.

**Comment by tylerflex** [comment]
Good catch, I made the appropriate change (to BatchData) and now that doesn't show any more except if the Batch.verbose = True. 

 I think this notebook will not be updated along with this PR, but I will make the suggested change to include in [this](https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/126) PR.

**Review by lucas-flexcompute — APPROVED** [review]

**Pull request merged**
