### PR TITLE
Replaced nlopt with scipy in dispersion fitter

### PR DESCRIPTION
**Pull request by tylerflex**
In an attempt to remove `nlopt` from requirements, this PR replaces `nlopt` with the `scipy.optimize.minimize` from scipy. 

It needs a 2nd pair of eyes on it to make sure I set up the constriaints and various parameters correctly, could you take a look Weiliang?

When running the dispersion fitter tests in `test/plugins`, I get similar (but slightly worse) final results:

with nlopt
```
_________________________________ test_dispersion _________________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 3.20e-01 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 3.20e-01
______________________________ test_dispersion_load _______________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 9.95e-02 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 9.95e-02
______________________________ test_dispersion_plot _______________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 9.95e-02 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 9.95e-02
__________________________ test_dispersion_set_wvg_range __________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 2.99e-01 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 2.99e-01
```

with scipy:
```
_________________________________ test_dispersion _________________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 4.05e-01 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 4.05e-01
______________________________ test_dispersion_load _______________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 9.95e-02 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 9.95e-02
______________________________ test_dispersion_plot _______________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 9.95e-02 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 9.95e-02
__________________________ test_dispersion_set_wvg_range __________________________
------------------------------ Captured stdout call -------------------------------
best RMS error so far: 3.31e-01 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
-------------------------------- Captured log call --------------------------------
WARNING  rich:fit.py:364 	warning: did not find fit with RMS error under tolerance_rms of 1.00e-02
INFO     rich:fit.py:368 	returning best fit with RMS error 3.31e-01
```

### CODE REVIEW

**Comment by momchil-flex** [comment]
What about having the *option* to use nlopt if installed, and using that on our webservice?

**Comment by weiliangjin2021** [comment]
> What about having the _option_ to use nlopt if installed, and using that on our webservice?

Webservice is largely independent of frontend code except for medium. So we can use NLOPT in webservice as long as we add NLOPT as requirement in webservice part independently.

**Comment by momchil-flex** [comment]
Well we need to keep the code that uses nlopt in here. I don't think we should have special code for the webservice. So what I'm suggesting is an extra parameter to the fit function, like `optimizer = ["scipy", "nlopt"]` or something (could be even more specific to which optimize function exactly to use from these packages), and in the webservice we just use the nlopt one. We can remove `nlopt` as a general dependence and raise an appropriate error prompting the user to try to install it if someone tries to run the fitter locally with nlopt optimizer and nlopt missing.

**Comment by tylerflex** [comment]
I guess if we can get scipy working as well as nlopt, i see no reason to
keep nlopt personally.

**Comment by momchil-flex** [comment]
Well, sure, but I'm dubious we'll be able to (there's a reason nlopt exists...)

**Comment by tylerflex** [comment]
Well with almost no effort i was able to get pretty close to nlopt in my PR
removing nlopt so i feel like it is probably possible

**Comment by weiliangjin2021** [comment]
One issue I read from scipy doc is that `constraints only workfor COBYLA, SLSQP and trust-constr`. So we need to check if we switch from Nelder-Mead to any of those algorithm, will the optimization be fast and converge to good result?

**Comment by weiliangjin2021** [comment]
Looks good, but we shouldn't change anything in `fit_web.py` yet. The webserivce will still be using NLOPT for now, and change it will cause compatibility issue.

**Comment by tylerflex** [comment]
Thanks @weiliangjin2021 , I guess the remaining question is how we should test how scipy works vs. nlopt. or whether this is even necessary with Momchil's recent changes in #452. I guess the main advantage of removing nlopt is to make it less likely users will have installation problems, like #441 , but if the performance of the fit is much worse, it's probably not worth it. If we test on the notebooks and `test_plugins.py` is that enough to say for sure that the scipy optimizer is working adequately?

**Comment by weiliangjin2021** [comment]
I think the test should be purely on webservice side, so nlopt can be completely removed from the fronted part.

**Comment by momchil-flex** [comment]
So can we go ahead and wrap this up?

**Comment by weiliangjin2021** [comment]
For the frontend, it should be good to go.

**Review by weiliangjin2021 — APPROVED** [review]

**Pull request merged**
