### PR TITLE
bump Jax-related versions

### PR DESCRIPTION
**Pull request by tylerflex**
@daquinteroflex 

I need to sort out some python installation stuff on my side. `poetry` is not working for me right now so I didnt' generate the new `.lock` file yet.

Just wondering if you think this versioning bump looks ok from your side. It's related to https://flow360.atlassian.net/browse/SCEM-5706

### CODE REVIEW

**Comment by daquinteroflex** [comment]
I had in my list in https://github.com/flexcompute/tidy3d/issues/1568 to "upgrade the jax requirements to caret and test across all platforms", maybe this is a good time if this is what we want to do, whilst we mantain the version limiting. That way we can consolidate it in a single requirement platform independent possibly. Happy to implement that since I had it pending and run the tests in poetry if you like, or feel free to do it if you prefer to instead?

**Comment by tylerflex** [comment]
Yea I think this is a good time, please go ahead. I tried generating the lock file but it was taking > 10 minutes. Is this normal? Could be that my hotel's internet is really bad too :D because it was taking a while to download all the requirements.

**Comment by daquinteroflex** [comment]
It did take some time to make the poetry lock. I think jaxlib is pretty big now. Made a PR to this PR https://github.com/flexcompute/tidy3d/pull/1597

**Review by daquinteroflex — APPROVED** [review]

**Comment by tylerflex** [comment]
I'm thinking maybe let's wait until 2.7.0rc1 is released before merging this, just in case.

FYI
@momchil-flex

**Comment by momchil-flex** [comment]
Done in #1622

**Pull request closed without merging**
