### PR TITLE
Improve web error display

### PR DESCRIPTION
**Pull request by An-Li-magicloud**
image

### CODE REVIEW

**Comment by momchil-flex** [comment]
Why not just `json.dumps(json_resp)["error"]` to only show the error message?

**Comment by momchil-flex** [comment]
Wait what I said doesn't make sense. I guess I don't understand why the old version doesn't work to just print the error message? It seems like it should be present in the dictionary. Maybe just removing the `resp.raise_for_status` line is enough?

**Comment by An-Li-magicloud** [comment]
> Wait what I said doesn't make sense. I guess I don't understand why the old version doesn't work to just print the error message? It seems like it should be present in the dictionary. Maybe just removing the `resp.raise_for_status` line is enough?

Either way, remove `resp.raise_for_status` works but the message doesn't easy to read:

**Comment by momchil-flex** [comment]
I don't know, the second option seems more standard to me, but it's true that the message is more visible in the first option. @tylerflex @xin-flex ?

**Comment by tylerflex** [comment]
Hm, so I'm not sure I understand. Are you saying that in the current state of the code, it will print
image

and in the PR version it will print
image

Joaquin's message seemed to miss the cause of the error entirely, maybe something changed on the backend since then?
image

Honestly, both 1st and 2nd are probably sufficient, but it might be better to display the message more prominently. Maybe we can raise a custom exception on the front end `if code == 4000000003` `from` the WebError that is created out of the json? Not sure if that would improve things, for example:

```py
        if resp.status_code != ResponseCodes.OK.value:
             if "error" in json_resp.keys():
                 e = WebError(json.dumps(json_resp, indent=4))
                 if "json_resp["code"] == 4000000003:
                     raise WebError("Insufficient credits.") from e
                 raise e
             resp.raise_for_status()
```
not sure if this is even valid python but if that improves readability maybe it's worth a try?

Otherwise, if the 1st screenshot is what we see currently, might want to just merge this after 2.0 in case it breaks anything.

**Comment by An-Li-magicloud** [comment]
We have reformat Java response in a json, just like the first screenshot, which is not only for balance, but all other api. So If you counter any error without json format, just like me know.

So we could just print out either entire json or just ``json["error"]``, but current code won't do neither because ``resp.raise_for_status()`` prevent that happens.

**Comment by tylerflex** [comment]
I see, thanks. I think maybe the 2nd option (`raise WebError(json["error"])`) might be my preference then. @An-Li-magicloud since we are releasing 2.0 today, do you think it's unlikely that this change will cause any bugs? just want to make sure because we did most of our testing earlier this week.

**Comment by tylerflex** [comment]
So yea I guess just removing the `resp.raise_for_status` line (like @momchil-flex said) would do the trick. I just tested a branch with that change and it worked fine (didn't test the actual error handling because I'm not sure how) but I'd say let's just remove that line and that should be good enough.

**Comment by tylerflex** [comment]
I made a PR with just this change + a changelog item so we could merge that if we go this route #817

**Comment by tylerflex** [comment]
ok merged #817 and so I'm closing this. Thanks @An-Li-magicloud for helping us figure this out and fix it!

**Pull request closed without merging**
